BMFILES=\
	gfx/pokemon/bulbasaur/bitmask.asm\
	gfx/pokemon/ivysaur/bitmask.asm\
	gfx/pokemon/venusaur/bitmask.asm\
	gfx/pokemon/charmander/bitmask.asm\
	gfx/pokemon/charmeleon/bitmask.asm\
	gfx/pokemon/charizard/bitmask.asm\
	gfx/pokemon/squirtle/bitmask.asm\
	gfx/pokemon/wartortle/bitmask.asm\
	gfx/pokemon/blastoise/bitmask.asm\
	gfx/pokemon/caterpie/bitmask.asm\
	gfx/pokemon/metapod/bitmask.asm\
	gfx/pokemon/butterfree/bitmask.asm\
	gfx/pokemon/weedle/bitmask.asm\
	gfx/pokemon/kakuna/bitmask.asm\
	gfx/pokemon/beedrill/bitmask.asm\
	gfx/pokemon/pidgey/bitmask.asm\
	gfx/pokemon/pidgeotto/bitmask.asm\
	gfx/pokemon/pidgeot/bitmask.asm\
	gfx/pokemon/rattata/bitmask.asm\
	gfx/pokemon/raticate/bitmask.asm\
	gfx/pokemon/spearow/bitmask.asm\
	gfx/pokemon/fearow/bitmask.asm\
	gfx/pokemon/ekans/bitmask.asm\
	gfx/pokemon/arbok/bitmask.asm\
	gfx/pokemon/pikachu/bitmask.asm\
	gfx/pokemon/raichu/bitmask.asm\
	gfx/pokemon/sandshrew/bitmask.asm\
	gfx/pokemon/sandslash/bitmask.asm\
	gfx/pokemon/nidoran_f/bitmask.asm\
	gfx/pokemon/nidorina/bitmask.asm\
	gfx/pokemon/nidoqueen/bitmask.asm\
	gfx/pokemon/nidoran_m/bitmask.asm\
	gfx/pokemon/nidorino/bitmask.asm\
	gfx/pokemon/nidoking/bitmask.asm\
	gfx/pokemon/clefairy/bitmask.asm\
	gfx/pokemon/clefable/bitmask.asm\
	gfx/pokemon/vulpix/bitmask.asm\
	gfx/pokemon/ninetales/bitmask.asm\
	gfx/pokemon/jigglypuff/bitmask.asm\
	gfx/pokemon/wigglytuff/bitmask.asm\
	gfx/pokemon/zubat/bitmask.asm\
	gfx/pokemon/golbat/bitmask.asm\
	gfx/pokemon/oddish/bitmask.asm\
	gfx/pokemon/gloom/bitmask.asm\
	gfx/pokemon/vileplume/bitmask.asm\
	gfx/pokemon/paras/bitmask.asm\
	gfx/pokemon/parasect/bitmask.asm\
	gfx/pokemon/venonat/bitmask.asm\
	gfx/pokemon/venomoth/bitmask.asm\
	gfx/pokemon/diglett/bitmask.asm\
	gfx/pokemon/dugtrio/bitmask.asm\
	gfx/pokemon/meowth/bitmask.asm\
	gfx/pokemon/persian/bitmask.asm\
	gfx/pokemon/psyduck/bitmask.asm\
	gfx/pokemon/golduck/bitmask.asm\
	gfx/pokemon/mankey/bitmask.asm\
	gfx/pokemon/primeape/bitmask.asm\
	gfx/pokemon/growlithe/bitmask.asm\
	gfx/pokemon/arcanine/bitmask.asm\
	gfx/pokemon/poliwag/bitmask.asm\
	gfx/pokemon/poliwhirl/bitmask.asm\
	gfx/pokemon/poliwrath/bitmask.asm\
	gfx/pokemon/abra/bitmask.asm\
	gfx/pokemon/kadabra/bitmask.asm\
	gfx/pokemon/alakazam/bitmask.asm\
	gfx/pokemon/machop/bitmask.asm\
	gfx/pokemon/machoke/bitmask.asm\
	gfx/pokemon/machamp/bitmask.asm\
	gfx/pokemon/bellsprout/bitmask.asm\
	gfx/pokemon/weepinbell/bitmask.asm\
	gfx/pokemon/victreebel/bitmask.asm\
	gfx/pokemon/tentacool/bitmask.asm\
	gfx/pokemon/tentacruel/bitmask.asm\
	gfx/pokemon/geodude/bitmask.asm\
	gfx/pokemon/graveler/bitmask.asm\
	gfx/pokemon/golem/bitmask.asm\
	gfx/pokemon/ponyta/bitmask.asm\
	gfx/pokemon/rapidash/bitmask.asm\
	gfx/pokemon/slowpoke/bitmask.asm\
	gfx/pokemon/slowbro/bitmask.asm\
	gfx/pokemon/magnemite/bitmask.asm\
	gfx/pokemon/magneton/bitmask.asm\
	gfx/pokemon/farfetch_d/bitmask.asm\
	gfx/pokemon/doduo/bitmask.asm\
	gfx/pokemon/dodrio/bitmask.asm\
	gfx/pokemon/seel/bitmask.asm\
	gfx/pokemon/dewgong/bitmask.asm\
	gfx/pokemon/grimer/bitmask.asm\
	gfx/pokemon/muk/bitmask.asm\
	gfx/pokemon/shellder/bitmask.asm\
	gfx/pokemon/cloyster/bitmask.asm\
	gfx/pokemon/gastly/bitmask.asm\
	gfx/pokemon/haunter/bitmask.asm\
	gfx/pokemon/gengar/bitmask.asm\
	gfx/pokemon/onix/bitmask.asm\
	gfx/pokemon/drowzee/bitmask.asm\
	gfx/pokemon/hypno/bitmask.asm\
	gfx/pokemon/krabby/bitmask.asm\
	gfx/pokemon/kingler/bitmask.asm\
	gfx/pokemon/voltorb/bitmask.asm\
	gfx/pokemon/electrode/bitmask.asm\
	gfx/pokemon/exeggcute/bitmask.asm\
	gfx/pokemon/exeggutor/bitmask.asm\
	gfx/pokemon/cubone/bitmask.asm\
	gfx/pokemon/marowak/bitmask.asm\
	gfx/pokemon/hitmonlee/bitmask.asm\
	gfx/pokemon/hitmonchan/bitmask.asm\
	gfx/pokemon/lickitung/bitmask.asm\
	gfx/pokemon/koffing/bitmask.asm\
	gfx/pokemon/weezing/bitmask.asm\
	gfx/pokemon/rhyhorn/bitmask.asm\
	gfx/pokemon/rhydon/bitmask.asm\
	gfx/pokemon/chansey/bitmask.asm\
	gfx/pokemon/tangela/bitmask.asm\
	gfx/pokemon/kangaskhan/bitmask.asm\
	gfx/pokemon/horsea/bitmask.asm\
	gfx/pokemon/seadra/bitmask.asm\
	gfx/pokemon/goldeen/bitmask.asm\
	gfx/pokemon/seaking/bitmask.asm\
	gfx/pokemon/staryu/bitmask.asm\
	gfx/pokemon/starmie/bitmask.asm\
	gfx/pokemon/mr__mime/bitmask.asm\
	gfx/pokemon/scyther/bitmask.asm\
	gfx/pokemon/jynx/bitmask.asm\
	gfx/pokemon/electabuzz/bitmask.asm\
	gfx/pokemon/magmar/bitmask.asm\
	gfx/pokemon/pinsir/bitmask.asm\
	gfx/pokemon/tauros/bitmask.asm\
	gfx/pokemon/magikarp/bitmask.asm\
	gfx/pokemon/gyarados/bitmask.asm\
	gfx/pokemon/lapras/bitmask.asm\
	gfx/pokemon/ditto/bitmask.asm\
	gfx/pokemon/eevee/bitmask.asm\
	gfx/pokemon/vaporeon/bitmask.asm\
	gfx/pokemon/jolteon/bitmask.asm\
	gfx/pokemon/flareon/bitmask.asm\
	gfx/pokemon/porygon/bitmask.asm\
	gfx/pokemon/omanyte/bitmask.asm\
	gfx/pokemon/omastar/bitmask.asm\
	gfx/pokemon/kabuto/bitmask.asm\
	gfx/pokemon/kabutops/bitmask.asm\
	gfx/pokemon/aerodactyl/bitmask.asm\
	gfx/pokemon/snorlax/bitmask.asm\
	gfx/pokemon/articuno/bitmask.asm\
	gfx/pokemon/zapdos/bitmask.asm\
	gfx/pokemon/moltres/bitmask.asm\
	gfx/pokemon/dratini/bitmask.asm\
	gfx/pokemon/dragonair/bitmask.asm\
	gfx/pokemon/dragonite/bitmask.asm\
	gfx/pokemon/mewtwo/bitmask.asm\
	gfx/pokemon/mew/bitmask.asm\
	gfx/pokemon/chikorita/bitmask.asm\
	gfx/pokemon/bayleef/bitmask.asm\
	gfx/pokemon/meganium/bitmask.asm\
	gfx/pokemon/cyndaquil/bitmask.asm\
	gfx/pokemon/quilava/bitmask.asm\
	gfx/pokemon/typhlosion/bitmask.asm\
	gfx/pokemon/totodile/bitmask.asm\
	gfx/pokemon/croconaw/bitmask.asm\
	gfx/pokemon/feraligatr/bitmask.asm\
	gfx/pokemon/sentret/bitmask.asm\
	gfx/pokemon/furret/bitmask.asm\
	gfx/pokemon/hoothoot/bitmask.asm\
	gfx/pokemon/noctowl/bitmask.asm\
	gfx/pokemon/ledyba/bitmask.asm\
	gfx/pokemon/ledian/bitmask.asm\
	gfx/pokemon/spinarak/bitmask.asm\
	gfx/pokemon/ariados/bitmask.asm\
	gfx/pokemon/crobat/bitmask.asm\
	gfx/pokemon/chinchou/bitmask.asm\
	gfx/pokemon/lanturn/bitmask.asm\
	gfx/pokemon/pichu/bitmask.asm\
	gfx/pokemon/cleffa/bitmask.asm\
	gfx/pokemon/igglybuff/bitmask.asm\
	gfx/pokemon/togepi/bitmask.asm\
	gfx/pokemon/togetic/bitmask.asm\
	gfx/pokemon/natu/bitmask.asm\
	gfx/pokemon/xatu/bitmask.asm\
	gfx/pokemon/mareep/bitmask.asm\
	gfx/pokemon/flaaffy/bitmask.asm\
	gfx/pokemon/ampharos/bitmask.asm\
	gfx/pokemon/bellossom/bitmask.asm\
	gfx/pokemon/marill/bitmask.asm\
	gfx/pokemon/azumarill/bitmask.asm\
	gfx/pokemon/sudowoodo/bitmask.asm\
	gfx/pokemon/politoed/bitmask.asm\
	gfx/pokemon/hoppip/bitmask.asm\
	gfx/pokemon/skiploom/bitmask.asm\
	gfx/pokemon/jumpluff/bitmask.asm\
	gfx/pokemon/aipom/bitmask.asm\
	gfx/pokemon/sunkern/bitmask.asm\
	gfx/pokemon/sunflora/bitmask.asm\
	gfx/pokemon/yanma/bitmask.asm\
	gfx/pokemon/wooper/bitmask.asm\
	gfx/pokemon/quagsire/bitmask.asm\
	gfx/pokemon/espeon/bitmask.asm\
	gfx/pokemon/umbreon/bitmask.asm\
	gfx/pokemon/murkrow/bitmask.asm\
	gfx/pokemon/slowking/bitmask.asm\
	gfx/pokemon/misdreavus/bitmask.asm\
	gfx/pokemon/wobbuffet/bitmask.asm\
	gfx/pokemon/girafarig/bitmask.asm\
	gfx/pokemon/pineco/bitmask.asm\
	gfx/pokemon/forretress/bitmask.asm\
	gfx/pokemon/dunsparce/bitmask.asm\
	gfx/pokemon/gligar/bitmask.asm\
	gfx/pokemon/steelix/bitmask.asm\
	gfx/pokemon/snubbull/bitmask.asm\
	gfx/pokemon/granbull/bitmask.asm\
	gfx/pokemon/qwilfish/bitmask.asm\
	gfx/pokemon/scizor/bitmask.asm\
	gfx/pokemon/shuckle/bitmask.asm\
	gfx/pokemon/heracross/bitmask.asm\
	gfx/pokemon/sneasel/bitmask.asm\
	gfx/pokemon/teddiursa/bitmask.asm\
	gfx/pokemon/ursaring/bitmask.asm\
	gfx/pokemon/slugma/bitmask.asm\
	gfx/pokemon/magcargo/bitmask.asm\
	gfx/pokemon/swinub/bitmask.asm\
	gfx/pokemon/piloswine/bitmask.asm\
	gfx/pokemon/corsola/bitmask.asm\
	gfx/pokemon/remoraid/bitmask.asm\
	gfx/pokemon/octillery/bitmask.asm\
	gfx/pokemon/delibird/bitmask.asm\
	gfx/pokemon/mantine/bitmask.asm\
	gfx/pokemon/skarmory/bitmask.asm\
	gfx/pokemon/houndour/bitmask.asm\
	gfx/pokemon/houndoom/bitmask.asm\
	gfx/pokemon/kingdra/bitmask.asm\
	gfx/pokemon/phanpy/bitmask.asm\
	gfx/pokemon/donphan/bitmask.asm\
	gfx/pokemon/porygon2/bitmask.asm\
	gfx/pokemon/stantler/bitmask.asm\
	gfx/pokemon/smeargle/bitmask.asm\
	gfx/pokemon/tyrogue/bitmask.asm\
	gfx/pokemon/hitmontop/bitmask.asm\
	gfx/pokemon/smoochum/bitmask.asm\
	gfx/pokemon/elekid/bitmask.asm\
	gfx/pokemon/magby/bitmask.asm\
	gfx/pokemon/miltank/bitmask.asm\
	gfx/pokemon/blissey/bitmask.asm\
	gfx/pokemon/raikou/bitmask.asm\
	gfx/pokemon/entei/bitmask.asm\
	gfx/pokemon/suicune/bitmask.asm\
	gfx/pokemon/larvitar/bitmask.asm\
	gfx/pokemon/pupitar/bitmask.asm\
	gfx/pokemon/tyranitar/bitmask.asm\
	gfx/pokemon/lugia/bitmask.asm\
	gfx/pokemon/ho_oh/bitmask.asm\
	gfx/pokemon/celebi/bitmask.asm\
	gfx/pokemon/egg/bitmask.asm\
	gfx/pokemon/unown_a/bitmask.asm\
	gfx/pokemon/unown_b/bitmask.asm\
	gfx/pokemon/unown_c/bitmask.asm\
	gfx/pokemon/unown_d/bitmask.asm\
	gfx/pokemon/unown_e/bitmask.asm\
	gfx/pokemon/unown_f/bitmask.asm\
	gfx/pokemon/unown_g/bitmask.asm\
	gfx/pokemon/unown_h/bitmask.asm\
	gfx/pokemon/unown_i/bitmask.asm\
	gfx/pokemon/unown_j/bitmask.asm\
	gfx/pokemon/unown_k/bitmask.asm\
	gfx/pokemon/unown_l/bitmask.asm\
	gfx/pokemon/unown_m/bitmask.asm\
	gfx/pokemon/unown_n/bitmask.asm\
	gfx/pokemon/unown_o/bitmask.asm\
	gfx/pokemon/unown_p/bitmask.asm\
	gfx/pokemon/unown_q/bitmask.asm\
	gfx/pokemon/unown_r/bitmask.asm\
	gfx/pokemon/unown_s/bitmask.asm\
	gfx/pokemon/unown_t/bitmask.asm\
	gfx/pokemon/unown_u/bitmask.asm\
	gfx/pokemon/unown_v/bitmask.asm\
	gfx/pokemon/unown_w/bitmask.asm\
	gfx/pokemon/unown_x/bitmask.asm\
	gfx/pokemon/unown_y/bitmask.asm\
	gfx/pokemon/unown_z/bitmask.asm\

FRFILES=\
	gfx/pokemon/unown_a/frames.asm\
	gfx/pokemon/unown_b/frames.asm\
	gfx/pokemon/unown_c/frames.asm\
	gfx/pokemon/unown_d/frames.asm\
	gfx/pokemon/unown_e/frames.asm\
	gfx/pokemon/unown_f/frames.asm\
	gfx/pokemon/unown_g/frames.asm\
	gfx/pokemon/unown_h/frames.asm\
	gfx/pokemon/unown_i/frames.asm\
	gfx/pokemon/unown_j/frames.asm\
	gfx/pokemon/unown_k/frames.asm\
	gfx/pokemon/unown_l/frames.asm\
	gfx/pokemon/unown_m/frames.asm\
	gfx/pokemon/unown_n/frames.asm\
	gfx/pokemon/unown_o/frames.asm\
	gfx/pokemon/unown_p/frames.asm\
	gfx/pokemon/unown_q/frames.asm\
	gfx/pokemon/unown_r/frames.asm\
	gfx/pokemon/unown_s/frames.asm\
	gfx/pokemon/unown_t/frames.asm\
	gfx/pokemon/unown_u/frames.asm\
	gfx/pokemon/unown_v/frames.asm\
	gfx/pokemon/unown_w/frames.asm\
	gfx/pokemon/unown_x/frames.asm\
	gfx/pokemon/unown_y/frames.asm\
	gfx/pokemon/unown_z/frames.asm\
	gfx/pokemon/bulbasaur/frames.asm\
	gfx/pokemon/ivysaur/frames.asm\
	gfx/pokemon/venusaur/frames.asm\
	gfx/pokemon/charmander/frames.asm\
	gfx/pokemon/charmeleon/frames.asm\
	gfx/pokemon/charizard/frames.asm\
	gfx/pokemon/squirtle/frames.asm\
	gfx/pokemon/wartortle/frames.asm\
	gfx/pokemon/blastoise/frames.asm\
	gfx/pokemon/caterpie/frames.asm\
	gfx/pokemon/metapod/frames.asm\
	gfx/pokemon/butterfree/frames.asm\
	gfx/pokemon/weedle/frames.asm\
	gfx/pokemon/kakuna/frames.asm\
	gfx/pokemon/beedrill/frames.asm\
	gfx/pokemon/pidgey/frames.asm\
	gfx/pokemon/pidgeotto/frames.asm\
	gfx/pokemon/pidgeot/frames.asm\
	gfx/pokemon/rattata/frames.asm\
	gfx/pokemon/raticate/frames.asm\
	gfx/pokemon/spearow/frames.asm\
	gfx/pokemon/fearow/frames.asm\
	gfx/pokemon/ekans/frames.asm\
	gfx/pokemon/arbok/frames.asm\
	gfx/pokemon/pikachu/frames.asm\
	gfx/pokemon/raichu/frames.asm\
	gfx/pokemon/sandshrew/frames.asm\
	gfx/pokemon/sandslash/frames.asm\
	gfx/pokemon/nidoran_f/frames.asm\
	gfx/pokemon/nidorina/frames.asm\
	gfx/pokemon/nidoqueen/frames.asm\
	gfx/pokemon/nidoran_m/frames.asm\
	gfx/pokemon/nidorino/frames.asm\
	gfx/pokemon/nidoking/frames.asm\
	gfx/pokemon/clefairy/frames.asm\
	gfx/pokemon/clefable/frames.asm\
	gfx/pokemon/vulpix/frames.asm\
	gfx/pokemon/ninetales/frames.asm\
	gfx/pokemon/jigglypuff/frames.asm\
	gfx/pokemon/wigglytuff/frames.asm\
	gfx/pokemon/zubat/frames.asm\
	gfx/pokemon/golbat/frames.asm\
	gfx/pokemon/oddish/frames.asm\
	gfx/pokemon/gloom/frames.asm\
	gfx/pokemon/vileplume/frames.asm\
	gfx/pokemon/paras/frames.asm\
	gfx/pokemon/parasect/frames.asm\
	gfx/pokemon/venonat/frames.asm\
	gfx/pokemon/venomoth/frames.asm\
	gfx/pokemon/diglett/frames.asm\
	gfx/pokemon/dugtrio/frames.asm\
	gfx/pokemon/meowth/frames.asm\
	gfx/pokemon/persian/frames.asm\
	gfx/pokemon/psyduck/frames.asm\
	gfx/pokemon/golduck/frames.asm\
	gfx/pokemon/mankey/frames.asm\
	gfx/pokemon/primeape/frames.asm\
	gfx/pokemon/growlithe/frames.asm\
	gfx/pokemon/arcanine/frames.asm\
	gfx/pokemon/poliwag/frames.asm\
	gfx/pokemon/poliwhirl/frames.asm\
	gfx/pokemon/poliwrath/frames.asm\
	gfx/pokemon/abra/frames.asm\
	gfx/pokemon/kadabra/frames.asm\
	gfx/pokemon/alakazam/frames.asm\
	gfx/pokemon/machop/frames.asm\
	gfx/pokemon/machoke/frames.asm\
	gfx/pokemon/machamp/frames.asm\
	gfx/pokemon/bellsprout/frames.asm\
	gfx/pokemon/weepinbell/frames.asm\
	gfx/pokemon/victreebel/frames.asm\
	gfx/pokemon/tentacool/frames.asm\
	gfx/pokemon/tentacruel/frames.asm\
	gfx/pokemon/geodude/frames.asm\
	gfx/pokemon/graveler/frames.asm\
	gfx/pokemon/golem/frames.asm\
	gfx/pokemon/ponyta/frames.asm\
	gfx/pokemon/rapidash/frames.asm\
	gfx/pokemon/slowpoke/frames.asm\
	gfx/pokemon/slowbro/frames.asm\
	gfx/pokemon/magnemite/frames.asm\
	gfx/pokemon/magneton/frames.asm\
	gfx/pokemon/farfetch_d/frames.asm\
	gfx/pokemon/doduo/frames.asm\
	gfx/pokemon/dodrio/frames.asm\
	gfx/pokemon/seel/frames.asm\
	gfx/pokemon/dewgong/frames.asm\
	gfx/pokemon/grimer/frames.asm\
	gfx/pokemon/muk/frames.asm\
	gfx/pokemon/shellder/frames.asm\
	gfx/pokemon/cloyster/frames.asm\
	gfx/pokemon/gastly/frames.asm\
	gfx/pokemon/haunter/frames.asm\
	gfx/pokemon/gengar/frames.asm\
	gfx/pokemon/onix/frames.asm\
	gfx/pokemon/drowzee/frames.asm\
	gfx/pokemon/hypno/frames.asm\
	gfx/pokemon/krabby/frames.asm\
	gfx/pokemon/kingler/frames.asm\
	gfx/pokemon/voltorb/frames.asm\
	gfx/pokemon/electrode/frames.asm\
	gfx/pokemon/exeggcute/frames.asm\
	gfx/pokemon/exeggutor/frames.asm\
	gfx/pokemon/cubone/frames.asm\
	gfx/pokemon/marowak/frames.asm\
	gfx/pokemon/hitmonlee/frames.asm\
	gfx/pokemon/hitmonchan/frames.asm\
	gfx/pokemon/lickitung/frames.asm\
	gfx/pokemon/koffing/frames.asm\
	gfx/pokemon/weezing/frames.asm\
	gfx/pokemon/rhyhorn/frames.asm\
	gfx/pokemon/rhydon/frames.asm\
	gfx/pokemon/chansey/frames.asm\
	gfx/pokemon/tangela/frames.asm\
	gfx/pokemon/kangaskhan/frames.asm\
	gfx/pokemon/horsea/frames.asm\
	gfx/pokemon/seadra/frames.asm\
	gfx/pokemon/goldeen/frames.asm\
	gfx/pokemon/seaking/frames.asm\
	gfx/pokemon/staryu/frames.asm\
	gfx/pokemon/starmie/frames.asm\
	gfx/pokemon/mr__mime/frames.asm\
	gfx/pokemon/scyther/frames.asm\
	gfx/pokemon/jynx/frames.asm\
	gfx/pokemon/electabuzz/frames.asm\
	gfx/pokemon/magmar/frames.asm\
	gfx/pokemon/pinsir/frames.asm\
	gfx/pokemon/tauros/frames.asm\
	gfx/pokemon/magikarp/frames.asm\
	gfx/pokemon/gyarados/frames.asm\
	gfx/pokemon/lapras/frames.asm\
	gfx/pokemon/ditto/frames.asm\
	gfx/pokemon/eevee/frames.asm\
	gfx/pokemon/vaporeon/frames.asm\
	gfx/pokemon/jolteon/frames.asm\
	gfx/pokemon/flareon/frames.asm\
	gfx/pokemon/porygon/frames.asm\
	gfx/pokemon/omanyte/frames.asm\
	gfx/pokemon/omastar/frames.asm\
	gfx/pokemon/kabuto/frames.asm\
	gfx/pokemon/kabutops/frames.asm\
	gfx/pokemon/aerodactyl/frames.asm\
	gfx/pokemon/snorlax/frames.asm\
	gfx/pokemon/articuno/frames.asm\
	gfx/pokemon/zapdos/frames.asm\
	gfx/pokemon/moltres/frames.asm\
	gfx/pokemon/dratini/frames.asm\
	gfx/pokemon/dragonair/frames.asm\
	gfx/pokemon/dragonite/frames.asm\
	gfx/pokemon/mewtwo/frames.asm\
	gfx/pokemon/mew/frames.asm\
	gfx/pokemon/chikorita/frames.asm\
	gfx/pokemon/bayleef/frames.asm\
	gfx/pokemon/meganium/frames.asm\
	gfx/pokemon/cyndaquil/frames.asm\
	gfx/pokemon/quilava/frames.asm\
	gfx/pokemon/typhlosion/frames.asm\
	gfx/pokemon/totodile/frames.asm\
	gfx/pokemon/croconaw/frames.asm\
	gfx/pokemon/feraligatr/frames.asm\
	gfx/pokemon/sentret/frames.asm\
	gfx/pokemon/furret/frames.asm\
	gfx/pokemon/hoothoot/frames.asm\
	gfx/pokemon/noctowl/frames.asm\
	gfx/pokemon/ledyba/frames.asm\
	gfx/pokemon/ledian/frames.asm\
	gfx/pokemon/spinarak/frames.asm\
	gfx/pokemon/ariados/frames.asm\
	gfx/pokemon/crobat/frames.asm\
	gfx/pokemon/chinchou/frames.asm\
	gfx/pokemon/lanturn/frames.asm\
	gfx/pokemon/pichu/frames.asm\
	gfx/pokemon/cleffa/frames.asm\
	gfx/pokemon/igglybuff/frames.asm\
	gfx/pokemon/togepi/frames.asm\
	gfx/pokemon/togetic/frames.asm\
	gfx/pokemon/natu/frames.asm\
	gfx/pokemon/xatu/frames.asm\
	gfx/pokemon/mareep/frames.asm\
	gfx/pokemon/flaaffy/frames.asm\
	gfx/pokemon/ampharos/frames.asm\
	gfx/pokemon/bellossom/frames.asm\
	gfx/pokemon/marill/frames.asm\
	gfx/pokemon/azumarill/frames.asm\
	gfx/pokemon/sudowoodo/frames.asm\
	gfx/pokemon/politoed/frames.asm\
	gfx/pokemon/hoppip/frames.asm\
	gfx/pokemon/skiploom/frames.asm\
	gfx/pokemon/jumpluff/frames.asm\
	gfx/pokemon/aipom/frames.asm\
	gfx/pokemon/sunkern/frames.asm\
	gfx/pokemon/sunflora/frames.asm\
	gfx/pokemon/yanma/frames.asm\
	gfx/pokemon/wooper/frames.asm\
	gfx/pokemon/quagsire/frames.asm\
	gfx/pokemon/espeon/frames.asm\
	gfx/pokemon/umbreon/frames.asm\
	gfx/pokemon/murkrow/frames.asm\
	gfx/pokemon/slowking/frames.asm\
	gfx/pokemon/misdreavus/frames.asm\
	gfx/pokemon/wobbuffet/frames.asm\
	gfx/pokemon/girafarig/frames.asm\
	gfx/pokemon/pineco/frames.asm\
	gfx/pokemon/forretress/frames.asm\
	gfx/pokemon/dunsparce/frames.asm\
	gfx/pokemon/gligar/frames.asm\
	gfx/pokemon/steelix/frames.asm\
	gfx/pokemon/snubbull/frames.asm\
	gfx/pokemon/granbull/frames.asm\
	gfx/pokemon/qwilfish/frames.asm\
	gfx/pokemon/scizor/frames.asm\
	gfx/pokemon/shuckle/frames.asm\
	gfx/pokemon/heracross/frames.asm\
	gfx/pokemon/sneasel/frames.asm\
	gfx/pokemon/teddiursa/frames.asm\
	gfx/pokemon/ursaring/frames.asm\
	gfx/pokemon/slugma/frames.asm\
	gfx/pokemon/magcargo/frames.asm\
	gfx/pokemon/swinub/frames.asm\
	gfx/pokemon/piloswine/frames.asm\
	gfx/pokemon/corsola/frames.asm\
	gfx/pokemon/remoraid/frames.asm\
	gfx/pokemon/octillery/frames.asm\
	gfx/pokemon/delibird/frames.asm\
	gfx/pokemon/mantine/frames.asm\
	gfx/pokemon/skarmory/frames.asm\
	gfx/pokemon/houndour/frames.asm\
	gfx/pokemon/houndoom/frames.asm\
	gfx/pokemon/kingdra/frames.asm\
	gfx/pokemon/phanpy/frames.asm\
	gfx/pokemon/donphan/frames.asm\
	gfx/pokemon/porygon2/frames.asm\
	gfx/pokemon/stantler/frames.asm\
	gfx/pokemon/smeargle/frames.asm\
	gfx/pokemon/tyrogue/frames.asm\
	gfx/pokemon/hitmontop/frames.asm\
	gfx/pokemon/smoochum/frames.asm\
	gfx/pokemon/elekid/frames.asm\
	gfx/pokemon/magby/frames.asm\
	gfx/pokemon/miltank/frames.asm\
	gfx/pokemon/blissey/frames.asm\
	gfx/pokemon/raikou/frames.asm\
	gfx/pokemon/entei/frames.asm\
	gfx/pokemon/suicune/frames.asm\
	gfx/pokemon/larvitar/frames.asm\
	gfx/pokemon/pupitar/frames.asm\
	gfx/pokemon/tyranitar/frames.asm\
	gfx/pokemon/lugia/frames.asm\
	gfx/pokemon/ho_oh/frames.asm\
	gfx/pokemon/celebi/frames.asm\
	gfx/pokemon/egg/frames.asm\

B2FILES=\
	gfx/tilesets/roofs/new_bark.2bpp\
	gfx/tilesets/roofs/violet.2bpp\
	gfx/tilesets/roofs/azalea.2bpp\
	gfx/tilesets/roofs/olivine.2bpp\
	gfx/tilesets/roofs/goldenrod.2bpp\
	gfx/overworld/trainer_battle_pokeball_tiles.2bpp\
	gfx/battle/balls.2bpp\
	gfx/battle/minimize.2bpp\
	gfx/debug/up_arrow.2bpp\
	gfx/debug/color_test.2bpp\
	gfx/tilesets/forest-tree/1.2bpp\
	gfx/tilesets/forest-tree/2.2bpp\
	gfx/tilesets/forest-tree/3.2bpp\
	gfx/tilesets/forest-tree/4.2bpp\
	gfx/overworld/cut_grass.2bpp\
	gfx/overworld/celebi.2bpp\
	gfx/overworld/headbutt_tree.2bpp\
	gfx/overworld/cut_tree.2bpp\
	gfx/overworld/cut_grass.2bpp\
	gfx/overworld/chris_fish.2bpp\
	gfx/overworld/kris_fish.2bpp\
	gfx/overworld/heal_machine.2bpp\
	gfx/font/feet_inches.2bpp\
	gfx/card_flip/off.2bpp\
	gfx/card_flip/on.2bpp\
	gfx/unown_puzzle/tile_borders.2bpp\
	gfx/unown_puzzle/cursor.2bpp\
	gfx/sgb/sgb_border.2bpp\
	gfx/font/overworld.2bpp\
	gfx/font/overworld_space.2bpp\
	gfx/stats/mail.2bpp\
	gfx/stats/item.2bpp\
	gfx/trainer_card/chris_card.2bpp\
	gfx/trainer_card/kris_card.2bpp\
	gfx/trainer_card/trainer_card.2bpp\
	gfx/player/chris.2bpp\
	gfx/player/kris.2bpp\
	gfx/player/kris_back.2bpp\
	gfx/battle/expbarend.2bpp\
	gfx/battle/expbarend_sgb.2bpp\
	gfx/pack/pack_menu.2bpp\
	gfx/pack/pack.2bpp\
	gfx/pack/pack_f.2bpp\
	gfx/trade/unused_gs_border_tiles.2bpp\
	gfx/trade/border_tiles.2bpp\
	gfx/mystery_gift/mystery_gift.2bpp\
	gfx/mystery_gift/card_trade.2bpp\
	gfx/mystery_gift/card_sprite.2bpp\
	gfx/new_game/gender_screen.2bpp\
	gfx/mobile/mobile_menu.2bpp\
	gfx/naming_screen/border.2bpp\
	gfx/naming_screen/cursor.2bpp\
	gfx/naming_screen/mail.2bpp\
	gfx/trainer_card/card_status.2bpp\
	gfx/trainer_card/leaders.2bpp\
	gfx/trainer_card/leaders.2bpp\
	gfx/trainer_card/badges.2bpp\
	gfx/trainer_card/badges.2bpp\
	gfx/trainer_card/card_right_corner.2bpp\
	gfx/credits/border.2bpp\
	gfx/credits/pichu.2bpp\
	gfx/credits/smoochum.2bpp\
	gfx/credits/ditto.2bpp\
	gfx/credits/igglybuff.2bpp\
	gfx/evo/bubble_large.2bpp\
	gfx/evo/bubble.2bpp\
	gfx/intro/grass1.2bpp\
	gfx/intro/grass2.2bpp\
	gfx/intro/grass3.2bpp\
	gfx/intro/grass4.2bpp\
	gfx/trade/arrow_right.2bpp\
	gfx/trade/arrow_left.2bpp\
	gfx/trade/cable.2bpp\
	gfx/trade/bubble.2bpp\
	gfx/trade/ball.2bpp\
	gfx/trade/poof.2bpp\
	gfx/title/old_bg.2bpp\
	gfx/title/old_fg.2bpp\
	gfx/pokegear/fast_ship.2bpp\
	gfx/pokegear/dexmap_nest_icon.2bpp\
	gfx/pc/pc_mail.2bpp\
	gfx/evo/egg_hatch.2bpp\
	gfx/font/space.2bpp\
	gfx/tilesets/fountain/1.2bpp\
	gfx/tilesets/fountain/2.2bpp\
	gfx/tilesets/fountain/3.2bpp\
	gfx/tilesets/fountain/4.2bpp\
	gfx/tilesets/fountain/5.2bpp\
	gfx/tilesets/water/water.2bpp\
	gfx/tilesets/forest-tree/1.2bpp\
	gfx/tilesets/forest-tree/2.2bpp\
	gfx/tilesets/forest-tree/3.2bpp\
	gfx/tilesets/forest-tree/4.2bpp\
	gfx/tilesets/flower/dmg_1.2bpp\
	gfx/tilesets/flower/cgb_1.2bpp\
	gfx/tilesets/flower/dmg_2.2bpp\
	gfx/tilesets/flower/cgb_2.2bpp\
	gfx/tilesets/lava/1.2bpp\
	gfx/tilesets/lava/2.2bpp\
	gfx/tilesets/lava/3.2bpp\
	gfx/tilesets/lava/4.2bpp\
	gfx/tilesets/tower-pillar/1.2bpp\
	gfx/tilesets/tower-pillar/2.2bpp\
	gfx/tilesets/tower-pillar/3.2bpp\
	gfx/tilesets/tower-pillar/4.2bpp\
	gfx/tilesets/tower-pillar/5.2bpp\
	gfx/tilesets/tower-pillar/6.2bpp\
	gfx/tilesets/tower-pillar/7.2bpp\
	gfx/tilesets/tower-pillar/8.2bpp\
	gfx/tilesets/tower-pillar/9.2bpp\
	gfx/tilesets/tower-pillar/10.2bpp\
	gfx/tilesets/whirlpool/1.2bpp\
	gfx/tilesets/whirlpool/2.2bpp\
	gfx/tilesets/whirlpool/3.2bpp\
	gfx/tilesets/whirlpool/4.2bpp\
	gfx/emotes/shock.2bpp\
	gfx/emotes/question.2bpp\
	gfx/emotes/happy.2bpp\
	gfx/emotes/sad.2bpp\
	gfx/emotes/heart.2bpp\
	gfx/emotes/bolt.2bpp\
	gfx/emotes/sleep.2bpp\
	gfx/emotes/fish.2bpp\
	gfx/overworld/shadow.2bpp\
	gfx/overworld/fishing_rod.2bpp\
	gfx/overworld/boulder_dust.2bpp\
	gfx/overworld/grass_rustle.2bpp\
	gfx/font/font_extra.2bpp\
	gfx/font/font_battle_extra.2bpp\
	gfx/stats/stats_tiles.2bpp\
	gfx/battle/expbar.2bpp\
	gfx/font/unused_weekday_kanji.2bpp\
	gfx/font/phone_icon.2bpp\
	gfx/font/space.2bpp\
	gfx/mobile/phone_tiles.2bpp\
	gfx/frames/map_entry_sign.2bpp\
	gfx/font/up_arrow.2bpp\
	gfx/icons/poliwag.2bpp\
	gfx/icons/jigglypuff.2bpp\
	gfx/icons/diglett.2bpp\
	gfx/icons/pikachu.2bpp\
	gfx/icons/staryu.2bpp\
	gfx/icons/fish.2bpp\
	gfx/icons/bird.2bpp\
	gfx/icons/monster.2bpp\
	gfx/icons/clefairy.2bpp\
	gfx/icons/oddish.2bpp\
	gfx/icons/bug.2bpp\
	gfx/icons/ghost.2bpp\
	gfx/icons/lapras.2bpp\
	gfx/icons/humanshape.2bpp\
	gfx/icons/fox.2bpp\
	gfx/icons/equine.2bpp\
	gfx/icons/shell.2bpp\
	gfx/icons/blob.2bpp\
	gfx/icons/serpent.2bpp\
	gfx/icons/voltorb.2bpp\
	gfx/icons/squirtle.2bpp\
	gfx/icons/bulbasaur.2bpp\
	gfx/icons/charmander.2bpp\
	gfx/icons/caterpillar.2bpp\
	gfx/icons/unown.2bpp\
	gfx/icons/geodude.2bpp\
	gfx/icons/fighter.2bpp\
	gfx/icons/egg.2bpp\
	gfx/icons/jellyfish.2bpp\
	gfx/icons/moth.2bpp\
	gfx/icons/bat.2bpp\
	gfx/icons/snorlax.2bpp\
	gfx/icons/ho_oh.2bpp\
	gfx/icons/lugia.2bpp\
	gfx/icons/gyarados.2bpp\
	gfx/icons/slowpoke.2bpp\
	gfx/icons/sudowoodo.2bpp\
	gfx/icons/bigmon.2bpp\
	gfx/credits/theend.2bpp\
	gfx/splash/copyright.2bpp\
	gfx/font/unown_font.2bpp\
	gfx/sprites/chris.2bpp\
	gfx/sprites/chris_bike.2bpp\
	gfx/sprites/gameboy_kid.2bpp\
	gfx/sprites/rival.2bpp\
	gfx/sprites/oak.2bpp\
	gfx/sprites/red.2bpp\
	gfx/sprites/blue.2bpp\
	gfx/sprites/bill.2bpp\
	gfx/sprites/elder.2bpp\
	gfx/sprites/janine.2bpp\
	gfx/sprites/kurt.2bpp\
	gfx/sprites/mom.2bpp\
	gfx/sprites/blaine.2bpp\
	gfx/sprites/reds_mom.2bpp\
	gfx/sprites/daisy.2bpp\
	gfx/sprites/elm.2bpp\
	gfx/sprites/will.2bpp\
	gfx/sprites/falkner.2bpp\
	gfx/sprites/whitney.2bpp\
	gfx/sprites/bugsy.2bpp\
	gfx/sprites/morty.2bpp\
	gfx/sprites/chuck.2bpp\
	gfx/sprites/jasmine.2bpp\
	gfx/sprites/pryce.2bpp\
	gfx/sprites/clair.2bpp\
	gfx/sprites/brock.2bpp\
	gfx/sprites/karen.2bpp\
	gfx/sprites/bruno.2bpp\
	gfx/sprites/misty.2bpp\
	gfx/sprites/lance.2bpp\
	gfx/sprites/surge.2bpp\
	gfx/sprites/erika.2bpp\
	gfx/sprites/koga.2bpp\
	gfx/sprites/sabrina.2bpp\
	gfx/sprites/cooltrainer_m.2bpp\
	gfx/sprites/cooltrainer_f.2bpp\
	gfx/sprites/bug_catcher.2bpp\
	gfx/sprites/twin.2bpp\
	gfx/sprites/youngster.2bpp\
	gfx/sprites/lass.2bpp\
	gfx/sprites/teacher.2bpp\
	gfx/sprites/beauty.2bpp\
	gfx/sprites/super_nerd.2bpp\
	gfx/sprites/rocker.2bpp\
	gfx/sprites/pokefan_m.2bpp\
	gfx/sprites/pokefan_f.2bpp\
	gfx/sprites/gramps.2bpp\
	gfx/sprites/granny.2bpp\
	gfx/sprites/swimmer_guy.2bpp\
	gfx/sprites/swimmer_girl.2bpp\
	gfx/sprites/big_snorlax.2bpp\
	gfx/sprites/surfing_pikachu.2bpp\
	gfx/sprites/rocket.2bpp\
	gfx/sprites/rocket_girl.2bpp\
	gfx/sprites/nurse.2bpp\
	gfx/sprites/link_receptionist.2bpp\
	gfx/sprites/clerk.2bpp\
	gfx/sprites/fisher.2bpp\
	gfx/sprites/fishing_guru.2bpp\
	gfx/sprites/scientist.2bpp\
	gfx/sprites/kimono_girl.2bpp\
	gfx/sprites/sage.2bpp\
	gfx/sprites/unused_guy.2bpp\
	gfx/sprites/gentleman.2bpp\
	gfx/sprites/black_belt.2bpp\
	gfx/sprites/receptionist.2bpp\
	gfx/sprites/officer.2bpp\
	gfx/sprites/cal.2bpp\
	gfx/sprites/slowpoke.2bpp\
	gfx/sprites/captain.2bpp\
	gfx/sprites/big_lapras.2bpp\
	gfx/sprites/gym_guide.2bpp\
	gfx/sprites/sailor.2bpp\
	gfx/sprites/biker.2bpp\
	gfx/sprites/pharmacist.2bpp\
	gfx/sprites/monster.2bpp\
	gfx/sprites/fairy.2bpp\
	gfx/sprites/bird.2bpp\
	gfx/sprites/dragon.2bpp\
	gfx/sprites/big_onix.2bpp\
	gfx/sprites/n64.2bpp\
	gfx/sprites/sudowoodo.2bpp\
	gfx/sprites/surf.2bpp\
	gfx/sprites/poke_ball.2bpp\
	gfx/sprites/pokedex.2bpp\
	gfx/sprites/paper.2bpp\
	gfx/sprites/virtual_boy.2bpp\
	gfx/sprites/old_link_receptionist.2bpp\
	gfx/sprites/rock.2bpp\
	gfx/sprites/boulder.2bpp\
	gfx/sprites/snes.2bpp\
	gfx/sprites/famicom.2bpp\
	gfx/sprites/fruit_tree.2bpp\
	gfx/sprites/gold_trophy.2bpp\
	gfx/sprites/silver_trophy.2bpp\
	gfx/sprites/kris.2bpp\
	gfx/sprites/kris_bike.2bpp\
	gfx/sprites/kurt_outside.2bpp\
	gfx/sprites/suicune.2bpp\
	gfx/sprites/entei.2bpp\
	gfx/sprites/raikou.2bpp\
	gfx/sprites/standing_youngster.2bpp\
	gfx/mobile/select_start.2bpp\
	gfx/mobile/ez_chat_cursor.2bpp\
	gfx/mobile/mobile_trade_lights.2bpp\
	gfx/mobile/dialing_frame.2bpp\
	gfx/mobile/mobile_cable_1.2bpp\
	gfx/mobile/mobile_cable_2.2bpp\
	gfx/mobile/dialing.2bpp\
	gfx/mobile/mobile_splash.2bpp\
	gfx/mobile/mobile_splash_check.2bpp\
	gfx/mobile/pichu_border.2bpp\
	gfx/mobile/ascii_font.2bpp\
	gfx/mobile/stadium2_n64.2bpp\
	gfx/mobile/card.2bpp\
	gfx/mobile/chris_silhouette.2bpp\
	gfx/mobile/kris_silhouette.2bpp\
	gfx/mobile/card_2.2bpp\
	gfx/mobile/card_large_sprite.2bpp\
	gfx/mobile/card_folder.2bpp\
	gfx/mobile/card_sprite.2bpp\
	gfx/mobile/dialpad.2bpp\
	gfx/mobile/dialpad_cursor.2bpp\
	gfx/mobile/card_list.2bpp\
	gfx/mobile/havewant.2bpp\
	gfx/mobile/select.2bpp\
	gfx/mobile/pokemon_news.2bpp\
	gfx/font/postal_mark.2bpp\

B1FILES=\
	gfx/printer/bold_a.1bpp\
	gfx/printer/bold_b.1bpp\
	gfx/naming_screen/end.1bpp\
	gfx/naming_screen/middle_line.1bpp\
	gfx/naming_screen/underline.1bpp\
	gfx/splash/gamefreak_presents.1bpp\
	gfx/splash/gamefreak_logo.1bpp\
	gfx/pokegear/flymap_label_border.1bpp\
	gfx/font/english.1bpp\
	gfx/font/french_german.1bpp\
	gfx/font/spanish_italian.1bpp\
	gfx/printer/hp.1bpp\
	gfx/printer/lv.1bpp\
	gfx/new_game/timeset_bg.1bpp\
	gfx/new_game/up_arrow.1bpp\
	gfx/new_game/down_arrow.1bpp\
	gfx/font/font.1bpp\
	gfx/frames/1.1bpp\
	gfx/frames/2.1bpp\
	gfx/frames/3.1bpp\
	gfx/frames/4.1bpp\
	gfx/frames/5.1bpp\
	gfx/frames/6.1bpp\
	gfx/frames/7.1bpp\
	gfx/frames/8.1bpp\
	gfx/frames/9.1bpp\
	gfx/battle/enemy_hp_bar_border.1bpp\
	gfx/battle/hp_exp_bar_border.1bpp\
	gfx/font/unused_bold_font.1bpp\
	gfx/font/black.1bpp\
	gfx/font/unused_up_arrow.1bpp\
	gfx/footprints/bulbasaur.1bpp\
	gfx/footprints/ivysaur.1bpp\
	gfx/footprints/venusaur.1bpp\
	gfx/footprints/charmander.1bpp\
	gfx/footprints/charmeleon.1bpp\
	gfx/footprints/charizard.1bpp\
	gfx/footprints/squirtle.1bpp\
	gfx/footprints/wartortle.1bpp\
	gfx/footprints/bulbasaur.1bpp\
	gfx/footprints/ivysaur.1bpp\
	gfx/footprints/venusaur.1bpp\
	gfx/footprints/charmander.1bpp\
	gfx/footprints/charmeleon.1bpp\
	gfx/footprints/charizard.1bpp\
	gfx/footprints/squirtle.1bpp\
	gfx/footprints/wartortle.1bpp\
	gfx/footprints/blastoise.1bpp\
	gfx/footprints/caterpie.1bpp\
	gfx/footprints/metapod.1bpp\
	gfx/footprints/butterfree.1bpp\
	gfx/footprints/weedle.1bpp\
	gfx/footprints/kakuna.1bpp\
	gfx/footprints/beedrill.1bpp\
	gfx/footprints/pidgey.1bpp\
	gfx/footprints/blastoise.1bpp\
	gfx/footprints/caterpie.1bpp\
	gfx/footprints/metapod.1bpp\
	gfx/footprints/butterfree.1bpp\
	gfx/footprints/weedle.1bpp\
	gfx/footprints/kakuna.1bpp\
	gfx/footprints/beedrill.1bpp\
	gfx/footprints/pidgey.1bpp\
	gfx/footprints/pidgeotto.1bpp\
	gfx/footprints/pidgeot.1bpp\
	gfx/footprints/rattata.1bpp\
	gfx/footprints/raticate.1bpp\
	gfx/footprints/spearow.1bpp\
	gfx/footprints/fearow.1bpp\
	gfx/footprints/ekans.1bpp\
	gfx/footprints/arbok.1bpp\
	gfx/footprints/pidgeotto.1bpp\
	gfx/footprints/pidgeot.1bpp\
	gfx/footprints/rattata.1bpp\
	gfx/footprints/raticate.1bpp\
	gfx/footprints/spearow.1bpp\
	gfx/footprints/fearow.1bpp\
	gfx/footprints/ekans.1bpp\
	gfx/footprints/arbok.1bpp\
	gfx/footprints/pikachu.1bpp\
	gfx/footprints/raichu.1bpp\
	gfx/footprints/sandshrew.1bpp\
	gfx/footprints/sandslash.1bpp\
	gfx/footprints/nidoran_f.1bpp\
	gfx/footprints/nidorina.1bpp\
	gfx/footprints/nidoqueen.1bpp\
	gfx/footprints/nidoran_m.1bpp\
	gfx/footprints/pikachu.1bpp\
	gfx/footprints/raichu.1bpp\
	gfx/footprints/sandshrew.1bpp\
	gfx/footprints/sandslash.1bpp\
	gfx/footprints/nidoran_f.1bpp\
	gfx/footprints/nidorina.1bpp\
	gfx/footprints/nidoqueen.1bpp\
	gfx/footprints/nidoran_m.1bpp\
	gfx/footprints/nidorino.1bpp\
	gfx/footprints/nidoking.1bpp\
	gfx/footprints/clefairy.1bpp\
	gfx/footprints/clefable.1bpp\
	gfx/footprints/vulpix.1bpp\
	gfx/footprints/ninetales.1bpp\
	gfx/footprints/jigglypuff.1bpp\
	gfx/footprints/wigglytuff.1bpp\
	gfx/footprints/nidorino.1bpp\
	gfx/footprints/nidoking.1bpp\
	gfx/footprints/clefairy.1bpp\
	gfx/footprints/clefable.1bpp\
	gfx/footprints/vulpix.1bpp\
	gfx/footprints/ninetales.1bpp\
	gfx/footprints/jigglypuff.1bpp\
	gfx/footprints/wigglytuff.1bpp\
	gfx/footprints/zubat.1bpp\
	gfx/footprints/golbat.1bpp\
	gfx/footprints/oddish.1bpp\
	gfx/footprints/gloom.1bpp\
	gfx/footprints/vileplume.1bpp\
	gfx/footprints/paras.1bpp\
	gfx/footprints/parasect.1bpp\
	gfx/footprints/venonat.1bpp\
	gfx/footprints/zubat.1bpp\
	gfx/footprints/golbat.1bpp\
	gfx/footprints/oddish.1bpp\
	gfx/footprints/gloom.1bpp\
	gfx/footprints/vileplume.1bpp\
	gfx/footprints/paras.1bpp\
	gfx/footprints/parasect.1bpp\
	gfx/footprints/venonat.1bpp\
	gfx/footprints/venomoth.1bpp\
	gfx/footprints/diglett.1bpp\
	gfx/footprints/dugtrio.1bpp\
	gfx/footprints/meowth.1bpp\
	gfx/footprints/persian.1bpp\
	gfx/footprints/psyduck.1bpp\
	gfx/footprints/golduck.1bpp\
	gfx/footprints/mankey.1bpp\
	gfx/footprints/venomoth.1bpp\
	gfx/footprints/diglett.1bpp\
	gfx/footprints/dugtrio.1bpp\
	gfx/footprints/meowth.1bpp\
	gfx/footprints/persian.1bpp\
	gfx/footprints/psyduck.1bpp\
	gfx/footprints/golduck.1bpp\
	gfx/footprints/mankey.1bpp\
	gfx/footprints/primeape.1bpp\
	gfx/footprints/growlithe.1bpp\
	gfx/footprints/arcanine.1bpp\
	gfx/footprints/poliwag.1bpp\
	gfx/footprints/poliwhirl.1bpp\
	gfx/footprints/poliwrath.1bpp\
	gfx/footprints/abra.1bpp\
	gfx/footprints/kadabra.1bpp\
	gfx/footprints/primeape.1bpp\
	gfx/footprints/growlithe.1bpp\
	gfx/footprints/arcanine.1bpp\
	gfx/footprints/poliwag.1bpp\
	gfx/footprints/poliwhirl.1bpp\
	gfx/footprints/poliwrath.1bpp\
	gfx/footprints/abra.1bpp\
	gfx/footprints/kadabra.1bpp\
	gfx/footprints/alakazam.1bpp\
	gfx/footprints/machop.1bpp\
	gfx/footprints/machoke.1bpp\
	gfx/footprints/machamp.1bpp\
	gfx/footprints/bellsprout.1bpp\
	gfx/footprints/weepinbell.1bpp\
	gfx/footprints/victreebel.1bpp\
	gfx/footprints/tentacool.1bpp\
	gfx/footprints/alakazam.1bpp\
	gfx/footprints/machop.1bpp\
	gfx/footprints/machoke.1bpp\
	gfx/footprints/machamp.1bpp\
	gfx/footprints/bellsprout.1bpp\
	gfx/footprints/weepinbell.1bpp\
	gfx/footprints/victreebel.1bpp\
	gfx/footprints/tentacool.1bpp\
	gfx/footprints/tentacruel.1bpp\
	gfx/footprints/geodude.1bpp\
	gfx/footprints/graveler.1bpp\
	gfx/footprints/golem.1bpp\
	gfx/footprints/ponyta.1bpp\
	gfx/footprints/rapidash.1bpp\
	gfx/footprints/slowpoke.1bpp\
	gfx/footprints/slowbro.1bpp\
	gfx/footprints/tentacruel.1bpp\
	gfx/footprints/geodude.1bpp\
	gfx/footprints/graveler.1bpp\
	gfx/footprints/golem.1bpp\
	gfx/footprints/ponyta.1bpp\
	gfx/footprints/rapidash.1bpp\
	gfx/footprints/slowpoke.1bpp\
	gfx/footprints/slowbro.1bpp\
	gfx/footprints/magnemite.1bpp\
	gfx/footprints/magneton.1bpp\
	gfx/footprints/farfetch_d.1bpp\
	gfx/footprints/doduo.1bpp\
	gfx/footprints/dodrio.1bpp\
	gfx/footprints/seel.1bpp\
	gfx/footprints/dewgong.1bpp\
	gfx/footprints/grimer.1bpp\
	gfx/footprints/magnemite.1bpp\
	gfx/footprints/magneton.1bpp\
	gfx/footprints/farfetch_d.1bpp\
	gfx/footprints/doduo.1bpp\
	gfx/footprints/dodrio.1bpp\
	gfx/footprints/seel.1bpp\
	gfx/footprints/dewgong.1bpp\
	gfx/footprints/grimer.1bpp\
	gfx/footprints/muk.1bpp\
	gfx/footprints/shellder.1bpp\
	gfx/footprints/cloyster.1bpp\
	gfx/footprints/gastly.1bpp\
	gfx/footprints/haunter.1bpp\
	gfx/footprints/gengar.1bpp\
	gfx/footprints/onix.1bpp\
	gfx/footprints/drowzee.1bpp\
	gfx/footprints/muk.1bpp\
	gfx/footprints/shellder.1bpp\
	gfx/footprints/cloyster.1bpp\
	gfx/footprints/gastly.1bpp\
	gfx/footprints/haunter.1bpp\
	gfx/footprints/gengar.1bpp\
	gfx/footprints/onix.1bpp\
	gfx/footprints/drowzee.1bpp\
	gfx/footprints/hypno.1bpp\
	gfx/footprints/krabby.1bpp\
	gfx/footprints/kingler.1bpp\
	gfx/footprints/voltorb.1bpp\
	gfx/footprints/electrode.1bpp\
	gfx/footprints/exeggcute.1bpp\
	gfx/footprints/exeggutor.1bpp\
	gfx/footprints/cubone.1bpp\
	gfx/footprints/hypno.1bpp\
	gfx/footprints/krabby.1bpp\
	gfx/footprints/kingler.1bpp\
	gfx/footprints/voltorb.1bpp\
	gfx/footprints/electrode.1bpp\
	gfx/footprints/exeggcute.1bpp\
	gfx/footprints/exeggutor.1bpp\
	gfx/footprints/cubone.1bpp\
	gfx/footprints/marowak.1bpp\
	gfx/footprints/hitmonlee.1bpp\
	gfx/footprints/hitmonchan.1bpp\
	gfx/footprints/lickitung.1bpp\
	gfx/footprints/koffing.1bpp\
	gfx/footprints/weezing.1bpp\
	gfx/footprints/rhyhorn.1bpp\
	gfx/footprints/rhydon.1bpp\
	gfx/footprints/marowak.1bpp\
	gfx/footprints/hitmonlee.1bpp\
	gfx/footprints/hitmonchan.1bpp\
	gfx/footprints/lickitung.1bpp\
	gfx/footprints/koffing.1bpp\
	gfx/footprints/weezing.1bpp\
	gfx/footprints/rhyhorn.1bpp\
	gfx/footprints/rhydon.1bpp\
	gfx/footprints/chansey.1bpp\
	gfx/footprints/tangela.1bpp\
	gfx/footprints/kangaskhan.1bpp\
	gfx/footprints/horsea.1bpp\
	gfx/footprints/seadra.1bpp\
	gfx/footprints/goldeen.1bpp\
	gfx/footprints/seaking.1bpp\
	gfx/footprints/staryu.1bpp\
	gfx/footprints/chansey.1bpp\
	gfx/footprints/tangela.1bpp\
	gfx/footprints/kangaskhan.1bpp\
	gfx/footprints/horsea.1bpp\
	gfx/footprints/seadra.1bpp\
	gfx/footprints/goldeen.1bpp\
	gfx/footprints/seaking.1bpp\
	gfx/footprints/staryu.1bpp\
	gfx/footprints/starmie.1bpp\
	gfx/footprints/mr__mime.1bpp\
	gfx/footprints/scyther.1bpp\
	gfx/footprints/jynx.1bpp\
	gfx/footprints/electabuzz.1bpp\
	gfx/footprints/magmar.1bpp\
	gfx/footprints/pinsir.1bpp\
	gfx/footprints/tauros.1bpp\
	gfx/footprints/starmie.1bpp\
	gfx/footprints/mr__mime.1bpp\
	gfx/footprints/scyther.1bpp\
	gfx/footprints/jynx.1bpp\
	gfx/footprints/electabuzz.1bpp\
	gfx/footprints/magmar.1bpp\
	gfx/footprints/pinsir.1bpp\
	gfx/footprints/tauros.1bpp\
	gfx/footprints/magikarp.1bpp\
	gfx/footprints/gyarados.1bpp\
	gfx/footprints/lapras.1bpp\
	gfx/footprints/ditto.1bpp\
	gfx/footprints/eevee.1bpp\
	gfx/footprints/vaporeon.1bpp\
	gfx/footprints/jolteon.1bpp\
	gfx/footprints/flareon.1bpp\
	gfx/footprints/magikarp.1bpp\
	gfx/footprints/gyarados.1bpp\
	gfx/footprints/lapras.1bpp\
	gfx/footprints/ditto.1bpp\
	gfx/footprints/eevee.1bpp\
	gfx/footprints/vaporeon.1bpp\
	gfx/footprints/jolteon.1bpp\
	gfx/footprints/flareon.1bpp\
	gfx/footprints/porygon.1bpp\
	gfx/footprints/omanyte.1bpp\
	gfx/footprints/omastar.1bpp\
	gfx/footprints/kabuto.1bpp\
	gfx/footprints/kabutops.1bpp\
	gfx/footprints/aerodactyl.1bpp\
	gfx/footprints/snorlax.1bpp\
	gfx/footprints/articuno.1bpp\
	gfx/footprints/porygon.1bpp\
	gfx/footprints/omanyte.1bpp\
	gfx/footprints/omastar.1bpp\
	gfx/footprints/kabuto.1bpp\
	gfx/footprints/kabutops.1bpp\
	gfx/footprints/aerodactyl.1bpp\
	gfx/footprints/snorlax.1bpp\
	gfx/footprints/articuno.1bpp\
	gfx/footprints/zapdos.1bpp\
	gfx/footprints/moltres.1bpp\
	gfx/footprints/dratini.1bpp\
	gfx/footprints/dragonair.1bpp\
	gfx/footprints/dragonite.1bpp\
	gfx/footprints/mewtwo.1bpp\
	gfx/footprints/mew.1bpp\
	gfx/footprints/chikorita.1bpp\
	gfx/footprints/zapdos.1bpp\
	gfx/footprints/moltres.1bpp\
	gfx/footprints/dratini.1bpp\
	gfx/footprints/dragonair.1bpp\
	gfx/footprints/dragonite.1bpp\
	gfx/footprints/mewtwo.1bpp\
	gfx/footprints/mew.1bpp\
	gfx/footprints/chikorita.1bpp\
	gfx/footprints/bayleef.1bpp\
	gfx/footprints/meganium.1bpp\
	gfx/footprints/cyndaquil.1bpp\
	gfx/footprints/quilava.1bpp\
	gfx/footprints/typhlosion.1bpp\
	gfx/footprints/totodile.1bpp\
	gfx/footprints/croconaw.1bpp\
	gfx/footprints/feraligatr.1bpp\
	gfx/footprints/bayleef.1bpp\
	gfx/footprints/meganium.1bpp\
	gfx/footprints/cyndaquil.1bpp\
	gfx/footprints/quilava.1bpp\
	gfx/footprints/typhlosion.1bpp\
	gfx/footprints/totodile.1bpp\
	gfx/footprints/croconaw.1bpp\
	gfx/footprints/feraligatr.1bpp\
	gfx/footprints/sentret.1bpp\
	gfx/footprints/furret.1bpp\
	gfx/footprints/hoothoot.1bpp\
	gfx/footprints/noctowl.1bpp\
	gfx/footprints/ledyba.1bpp\
	gfx/footprints/ledian.1bpp\
	gfx/footprints/spinarak.1bpp\
	gfx/footprints/ariados.1bpp\
	gfx/footprints/sentret.1bpp\
	gfx/footprints/furret.1bpp\
	gfx/footprints/hoothoot.1bpp\
	gfx/footprints/noctowl.1bpp\
	gfx/footprints/ledyba.1bpp\
	gfx/footprints/ledian.1bpp\
	gfx/footprints/spinarak.1bpp\
	gfx/footprints/ariados.1bpp\
	gfx/footprints/crobat.1bpp\
	gfx/footprints/chinchou.1bpp\
	gfx/footprints/lanturn.1bpp\
	gfx/footprints/pichu.1bpp\
	gfx/footprints/cleffa.1bpp\
	gfx/footprints/igglybuff.1bpp\
	gfx/footprints/togepi.1bpp\
	gfx/footprints/togetic.1bpp\
	gfx/footprints/crobat.1bpp\
	gfx/footprints/chinchou.1bpp\
	gfx/footprints/lanturn.1bpp\
	gfx/footprints/pichu.1bpp\
	gfx/footprints/cleffa.1bpp\
	gfx/footprints/igglybuff.1bpp\
	gfx/footprints/togepi.1bpp\
	gfx/footprints/togetic.1bpp\
	gfx/footprints/natu.1bpp\
	gfx/footprints/xatu.1bpp\
	gfx/footprints/mareep.1bpp\
	gfx/footprints/flaaffy.1bpp\
	gfx/footprints/ampharos.1bpp\
	gfx/footprints/bellossom.1bpp\
	gfx/footprints/marill.1bpp\
	gfx/footprints/azumarill.1bpp\
	gfx/footprints/natu.1bpp\
	gfx/footprints/xatu.1bpp\
	gfx/footprints/mareep.1bpp\
	gfx/footprints/flaaffy.1bpp\
	gfx/footprints/ampharos.1bpp\
	gfx/footprints/bellossom.1bpp\
	gfx/footprints/marill.1bpp\
	gfx/footprints/azumarill.1bpp\
	gfx/footprints/sudowoodo.1bpp\
	gfx/footprints/politoed.1bpp\
	gfx/footprints/hoppip.1bpp\
	gfx/footprints/skiploom.1bpp\
	gfx/footprints/jumpluff.1bpp\
	gfx/footprints/aipom.1bpp\
	gfx/footprints/sunkern.1bpp\
	gfx/footprints/sunflora.1bpp\
	gfx/footprints/sudowoodo.1bpp\
	gfx/footprints/politoed.1bpp\
	gfx/footprints/hoppip.1bpp\
	gfx/footprints/skiploom.1bpp\
	gfx/footprints/jumpluff.1bpp\
	gfx/footprints/aipom.1bpp\
	gfx/footprints/sunkern.1bpp\
	gfx/footprints/sunflora.1bpp\
	gfx/footprints/yanma.1bpp\
	gfx/footprints/wooper.1bpp\
	gfx/footprints/quagsire.1bpp\
	gfx/footprints/espeon.1bpp\
	gfx/footprints/umbreon.1bpp\
	gfx/footprints/murkrow.1bpp\
	gfx/footprints/slowking.1bpp\
	gfx/footprints/misdreavus.1bpp\
	gfx/footprints/yanma.1bpp\
	gfx/footprints/wooper.1bpp\
	gfx/footprints/quagsire.1bpp\
	gfx/footprints/espeon.1bpp\
	gfx/footprints/umbreon.1bpp\
	gfx/footprints/murkrow.1bpp\
	gfx/footprints/slowking.1bpp\
	gfx/footprints/misdreavus.1bpp\
	gfx/footprints/unown.1bpp\
	gfx/footprints/wobbuffet.1bpp\
	gfx/footprints/girafarig.1bpp\
	gfx/footprints/pineco.1bpp\
	gfx/footprints/forretress.1bpp\
	gfx/footprints/dunsparce.1bpp\
	gfx/footprints/gligar.1bpp\
	gfx/footprints/steelix.1bpp\
	gfx/footprints/unown.1bpp\
	gfx/footprints/wobbuffet.1bpp\
	gfx/footprints/girafarig.1bpp\
	gfx/footprints/pineco.1bpp\
	gfx/footprints/forretress.1bpp\
	gfx/footprints/dunsparce.1bpp\
	gfx/footprints/gligar.1bpp\
	gfx/footprints/steelix.1bpp\
	gfx/footprints/snubbull.1bpp\
	gfx/footprints/granbull.1bpp\
	gfx/footprints/qwilfish.1bpp\
	gfx/footprints/scizor.1bpp\
	gfx/footprints/shuckle.1bpp\
	gfx/footprints/heracross.1bpp\
	gfx/footprints/sneasel.1bpp\
	gfx/footprints/teddiursa.1bpp\
	gfx/footprints/snubbull.1bpp\
	gfx/footprints/granbull.1bpp\
	gfx/footprints/qwilfish.1bpp\
	gfx/footprints/scizor.1bpp\
	gfx/footprints/shuckle.1bpp\
	gfx/footprints/heracross.1bpp\
	gfx/footprints/sneasel.1bpp\
	gfx/footprints/teddiursa.1bpp\
	gfx/footprints/ursaring.1bpp\
	gfx/footprints/slugma.1bpp\
	gfx/footprints/magcargo.1bpp\
	gfx/footprints/swinub.1bpp\
	gfx/footprints/piloswine.1bpp\
	gfx/footprints/corsola.1bpp\
	gfx/footprints/remoraid.1bpp\
	gfx/footprints/octillery.1bpp\
	gfx/footprints/ursaring.1bpp\
	gfx/footprints/slugma.1bpp\
	gfx/footprints/magcargo.1bpp\
	gfx/footprints/swinub.1bpp\
	gfx/footprints/piloswine.1bpp\
	gfx/footprints/corsola.1bpp\
	gfx/footprints/remoraid.1bpp\
	gfx/footprints/octillery.1bpp\
	gfx/footprints/delibird.1bpp\
	gfx/footprints/mantine.1bpp\
	gfx/footprints/skarmory.1bpp\
	gfx/footprints/houndour.1bpp\
	gfx/footprints/houndoom.1bpp\
	gfx/footprints/kingdra.1bpp\
	gfx/footprints/phanpy.1bpp\
	gfx/footprints/donphan.1bpp\
	gfx/footprints/delibird.1bpp\
	gfx/footprints/mantine.1bpp\
	gfx/footprints/skarmory.1bpp\
	gfx/footprints/houndour.1bpp\
	gfx/footprints/houndoom.1bpp\
	gfx/footprints/kingdra.1bpp\
	gfx/footprints/phanpy.1bpp\
	gfx/footprints/donphan.1bpp\
	gfx/footprints/porygon2.1bpp\
	gfx/footprints/stantler.1bpp\
	gfx/footprints/smeargle.1bpp\
	gfx/footprints/tyrogue.1bpp\
	gfx/footprints/hitmontop.1bpp\
	gfx/footprints/smoochum.1bpp\
	gfx/footprints/elekid.1bpp\
	gfx/footprints/magby.1bpp\
	gfx/footprints/porygon2.1bpp\
	gfx/footprints/stantler.1bpp\
	gfx/footprints/smeargle.1bpp\
	gfx/footprints/tyrogue.1bpp\
	gfx/footprints/hitmontop.1bpp\
	gfx/footprints/smoochum.1bpp\
	gfx/footprints/elekid.1bpp\
	gfx/footprints/magby.1bpp\
	gfx/footprints/miltank.1bpp\
	gfx/footprints/blissey.1bpp\
	gfx/footprints/raikou.1bpp\
	gfx/footprints/entei.1bpp\
	gfx/footprints/suicune.1bpp\
	gfx/footprints/larvitar.1bpp\
	gfx/footprints/pupitar.1bpp\
	gfx/footprints/tyranitar.1bpp\
	gfx/footprints/miltank.1bpp\
	gfx/footprints/blissey.1bpp\
	gfx/footprints/raikou.1bpp\
	gfx/footprints/entei.1bpp\
	gfx/footprints/suicune.1bpp\
	gfx/footprints/larvitar.1bpp\
	gfx/footprints/pupitar.1bpp\
	gfx/footprints/tyranitar.1bpp\
	gfx/footprints/lugia.1bpp\
	gfx/footprints/ho_oh.1bpp\
	gfx/footprints/celebi.1bpp\
	gfx/footprints/252.1bpp\
	gfx/footprints/253.1bpp\
	gfx/footprints/254.1bpp\
	gfx/footprints/255.1bpp\
	gfx/footprints/256.1bpp\
	gfx/footprints/lugia.1bpp\
	gfx/footprints/ho_oh.1bpp\
	gfx/footprints/celebi.1bpp\
	gfx/footprints/252.1bpp\
	gfx/footprints/253.1bpp\
	gfx/footprints/254.1bpp\
	gfx/footprints/255.1bpp\
	gfx/footprints/256.1bpp\
	gfx/mail/morph_mail_divider.1bpp\
	gfx/mail/grass.1bpp\
	gfx/mail/small_pokeball.1bpp\
	gfx/mail/morph_mail_border.1bpp\
	gfx/mail/small_note.1bpp\
	gfx/mail/wave.1bpp\
	gfx/mail/portraitmail_underline.1bpp\
	gfx/mail/lovely_mail_underline.1bpp\
	gfx/mail/small_heart.1bpp\
	gfx/mail/small_triangle.1bpp\
	gfx/mail/eon_mail_border_1.1bpp\
	gfx/mail/eon_mail_border_2.1bpp\
	gfx/mail/natu.1bpp\
	gfx/mail/dratini.1bpp\
	gfx/mail/poliwag.1bpp\
	gfx/mail/lapras.1bpp\
	gfx/mail/eevee.1bpp\
	gfx/mail/ditto.1bpp\
	gfx/mail/mew.1bpp\
	gfx/mail/dragonite.1bpp\
	gfx/mail/sentret.1bpp\
	gfx/mail/large_pokeball.1bpp\
	gfx/mail/oddish.1bpp\
	gfx/mail/large_triangle.1bpp\
	gfx/mail/large_heart.1bpp\
	gfx/mail/morph_mail_corner.1bpp\
	gfx/mail/large_circle.1bpp\
	gfx/mail/flower_1.1bpp\
	gfx/mail/flower_2.1bpp\
	gfx/mail/large_note.1bpp\
	gfx/mail/cloud.1bpp\
	gfx/mail/surf_mail_border.1bpp\
	gfx/mail/flower_mail_border.1bpp\
	gfx/mail/litebluemail_border.1bpp\
	gfx/mail/music_mail_border.1bpp\
	gfx/mail/lovely_mail_border.1bpp\
	gfx/mail/portraitmail_border.1bpp\
	gfx/font/font_inversed.1bpp\
	gfx/mobile/up_arrow.1bpp\
	gfx/mobile/down_arrow.1bpp\

DIMFILES=\
	gfx/pokemon/abra/front.dimensions\
	gfx/pokemon/aerodactyl/front.dimensions\
	gfx/pokemon/aipom/front.dimensions\
	gfx/pokemon/alakazam/front.dimensions\
	gfx/pokemon/ampharos/front.dimensions\
	gfx/pokemon/arbok/front.dimensions\
	gfx/pokemon/arcanine/front.dimensions\
	gfx/pokemon/ariados/front.dimensions\
	gfx/pokemon/articuno/front.dimensions\
	gfx/pokemon/azumarill/front.dimensions\
	gfx/pokemon/bayleef/front.dimensions\
	gfx/pokemon/beedrill/front.dimensions\
	gfx/pokemon/bellossom/front.dimensions\
	gfx/pokemon/bellsprout/front.dimensions\
	gfx/pokemon/blastoise/front.dimensions\
	gfx/pokemon/blissey/front.dimensions\
	gfx/pokemon/bulbasaur/front.dimensions\
	gfx/pokemon/butterfree/front.dimensions\
	gfx/pokemon/caterpie/front.dimensions\
	gfx/pokemon/celebi/front.dimensions\
	gfx/pokemon/chansey/front.dimensions\
	gfx/pokemon/charizard/front.dimensions\
	gfx/pokemon/charmander/front.dimensions\
	gfx/pokemon/charmeleon/front.dimensions\
	gfx/pokemon/chikorita/front.dimensions\
	gfx/pokemon/chinchou/front.dimensions\
	gfx/pokemon/clefable/front.dimensions\
	gfx/pokemon/clefairy/front.dimensions\
	gfx/pokemon/cleffa/front.dimensions\
	gfx/pokemon/cloyster/front.dimensions\
	gfx/pokemon/corsola/front.dimensions\
	gfx/pokemon/crobat/front.dimensions\
	gfx/pokemon/croconaw/front.dimensions\
	gfx/pokemon/cubone/front.dimensions\
	gfx/pokemon/cyndaquil/front.dimensions\
	gfx/pokemon/delibird/front.dimensions\
	gfx/pokemon/dewgong/front.dimensions\
	gfx/pokemon/diglett/front.dimensions\
	gfx/pokemon/ditto/front.dimensions\
	gfx/pokemon/dodrio/front.dimensions\
	gfx/pokemon/doduo/front.dimensions\
	gfx/pokemon/donphan/front.dimensions\
	gfx/pokemon/dragonair/front.dimensions\
	gfx/pokemon/dragonite/front.dimensions\
	gfx/pokemon/dratini/front.dimensions\
	gfx/pokemon/drowzee/front.dimensions\
	gfx/pokemon/dugtrio/front.dimensions\
	gfx/pokemon/dunsparce/front.dimensions\
	gfx/pokemon/eevee/front.dimensions\
	gfx/pokemon/ekans/front.dimensions\
	gfx/pokemon/electabuzz/front.dimensions\
	gfx/pokemon/electrode/front.dimensions\
	gfx/pokemon/elekid/front.dimensions\
	gfx/pokemon/entei/front.dimensions\
	gfx/pokemon/espeon/front.dimensions\
	gfx/pokemon/exeggcute/front.dimensions\
	gfx/pokemon/exeggutor/front.dimensions\
	gfx/pokemon/farfetch_d/front.dimensions\
	gfx/pokemon/fearow/front.dimensions\
	gfx/pokemon/feraligatr/front.dimensions\
	gfx/pokemon/flaaffy/front.dimensions\
	gfx/pokemon/flareon/front.dimensions\
	gfx/pokemon/forretress/front.dimensions\
	gfx/pokemon/furret/front.dimensions\
	gfx/pokemon/gastly/front.dimensions\
	gfx/pokemon/gengar/front.dimensions\
	gfx/pokemon/geodude/front.dimensions\
	gfx/pokemon/girafarig/front.dimensions\
	gfx/pokemon/gligar/front.dimensions\
	gfx/pokemon/gloom/front.dimensions\
	gfx/pokemon/golbat/front.dimensions\
	gfx/pokemon/goldeen/front.dimensions\
	gfx/pokemon/golduck/front.dimensions\
	gfx/pokemon/golem/front.dimensions\
	gfx/pokemon/granbull/front.dimensions\
	gfx/pokemon/graveler/front.dimensions\
	gfx/pokemon/grimer/front.dimensions\
	gfx/pokemon/growlithe/front.dimensions\
	gfx/pokemon/gyarados/front.dimensions\
	gfx/pokemon/haunter/front.dimensions\
	gfx/pokemon/heracross/front.dimensions\
	gfx/pokemon/hitmonchan/front.dimensions\
	gfx/pokemon/hitmonlee/front.dimensions\
	gfx/pokemon/hitmontop/front.dimensions\
	gfx/pokemon/ho_oh/front.dimensions\
	gfx/pokemon/hoothoot/front.dimensions\
	gfx/pokemon/hoppip/front.dimensions\
	gfx/pokemon/horsea/front.dimensions\
	gfx/pokemon/houndoom/front.dimensions\
	gfx/pokemon/houndour/front.dimensions\
	gfx/pokemon/hypno/front.dimensions\
	gfx/pokemon/igglybuff/front.dimensions\
	gfx/pokemon/ivysaur/front.dimensions\
	gfx/pokemon/jigglypuff/front.dimensions\
	gfx/pokemon/jolteon/front.dimensions\
	gfx/pokemon/jumpluff/front.dimensions\
	gfx/pokemon/jynx/front.dimensions\
	gfx/pokemon/kabuto/front.dimensions\
	gfx/pokemon/kabutops/front.dimensions\
	gfx/pokemon/kadabra/front.dimensions\
	gfx/pokemon/kakuna/front.dimensions\
	gfx/pokemon/kangaskhan/front.dimensions\
	gfx/pokemon/kingdra/front.dimensions\
	gfx/pokemon/kingler/front.dimensions\
	gfx/pokemon/koffing/front.dimensions\
	gfx/pokemon/krabby/front.dimensions\
	gfx/pokemon/lanturn/front.dimensions\
	gfx/pokemon/lapras/front.dimensions\
	gfx/pokemon/larvitar/front.dimensions\
	gfx/pokemon/ledian/front.dimensions\
	gfx/pokemon/ledyba/front.dimensions\
	gfx/pokemon/lickitung/front.dimensions\
	gfx/pokemon/lugia/front.dimensions\
	gfx/pokemon/machamp/front.dimensions\
	gfx/pokemon/machoke/front.dimensions\
	gfx/pokemon/machop/front.dimensions\
	gfx/pokemon/magby/front.dimensions\
	gfx/pokemon/magcargo/front.dimensions\
	gfx/pokemon/magikarp/front.dimensions\
	gfx/pokemon/magmar/front.dimensions\
	gfx/pokemon/magnemite/front.dimensions\
	gfx/pokemon/magneton/front.dimensions\
	gfx/pokemon/mankey/front.dimensions\
	gfx/pokemon/mantine/front.dimensions\
	gfx/pokemon/mareep/front.dimensions\
	gfx/pokemon/marill/front.dimensions\
	gfx/pokemon/marowak/front.dimensions\
	gfx/pokemon/meganium/front.dimensions\
	gfx/pokemon/meowth/front.dimensions\
	gfx/pokemon/metapod/front.dimensions\
	gfx/pokemon/mew/front.dimensions\
	gfx/pokemon/mewtwo/front.dimensions\
	gfx/pokemon/miltank/front.dimensions\
	gfx/pokemon/misdreavus/front.dimensions\
	gfx/pokemon/moltres/front.dimensions\
	gfx/pokemon/mr__mime/front.dimensions\
	gfx/pokemon/muk/front.dimensions\
	gfx/pokemon/murkrow/front.dimensions\
	gfx/pokemon/natu/front.dimensions\
	gfx/pokemon/nidoking/front.dimensions\
	gfx/pokemon/nidoqueen/front.dimensions\
	gfx/pokemon/nidoran_f/front.dimensions\
	gfx/pokemon/nidoran_m/front.dimensions\
	gfx/pokemon/nidorina/front.dimensions\
	gfx/pokemon/nidorino/front.dimensions\
	gfx/pokemon/ninetales/front.dimensions\
	gfx/pokemon/noctowl/front.dimensions\
	gfx/pokemon/octillery/front.dimensions\
	gfx/pokemon/oddish/front.dimensions\
	gfx/pokemon/omanyte/front.dimensions\
	gfx/pokemon/omastar/front.dimensions\
	gfx/pokemon/onix/front.dimensions\
	gfx/pokemon/paras/front.dimensions\
	gfx/pokemon/parasect/front.dimensions\
	gfx/pokemon/persian/front.dimensions\
	gfx/pokemon/phanpy/front.dimensions\
	gfx/pokemon/pichu/front.dimensions\
	gfx/pokemon/pidgeot/front.dimensions\
	gfx/pokemon/pidgeotto/front.dimensions\
	gfx/pokemon/pidgey/front.dimensions\
	gfx/pokemon/pikachu/front.dimensions\
	gfx/pokemon/piloswine/front.dimensions\
	gfx/pokemon/pineco/front.dimensions\
	gfx/pokemon/pinsir/front.dimensions\
	gfx/pokemon/politoed/front.dimensions\
	gfx/pokemon/poliwag/front.dimensions\
	gfx/pokemon/poliwhirl/front.dimensions\
	gfx/pokemon/poliwrath/front.dimensions\
	gfx/pokemon/ponyta/front.dimensions\
	gfx/pokemon/porygon/front.dimensions\
	gfx/pokemon/porygon2/front.dimensions\
	gfx/pokemon/primeape/front.dimensions\
	gfx/pokemon/psyduck/front.dimensions\
	gfx/pokemon/pupitar/front.dimensions\
	gfx/pokemon/quagsire/front.dimensions\
	gfx/pokemon/quilava/front.dimensions\
	gfx/pokemon/qwilfish/front.dimensions\
	gfx/pokemon/raichu/front.dimensions\
	gfx/pokemon/raikou/front.dimensions\
	gfx/pokemon/rapidash/front.dimensions\
	gfx/pokemon/raticate/front.dimensions\
	gfx/pokemon/rattata/front.dimensions\
	gfx/pokemon/remoraid/front.dimensions\
	gfx/pokemon/rhydon/front.dimensions\
	gfx/pokemon/rhyhorn/front.dimensions\
	gfx/pokemon/sandshrew/front.dimensions\
	gfx/pokemon/sandslash/front.dimensions\
	gfx/pokemon/scizor/front.dimensions\
	gfx/pokemon/scyther/front.dimensions\
	gfx/pokemon/seadra/front.dimensions\
	gfx/pokemon/seaking/front.dimensions\
	gfx/pokemon/seel/front.dimensions\
	gfx/pokemon/sentret/front.dimensions\
	gfx/pokemon/shellder/front.dimensions\
	gfx/pokemon/shuckle/front.dimensions\
	gfx/pokemon/skarmory/front.dimensions\
	gfx/pokemon/skiploom/front.dimensions\
	gfx/pokemon/slowbro/front.dimensions\
	gfx/pokemon/slowking/front.dimensions\
	gfx/pokemon/slowpoke/front.dimensions\
	gfx/pokemon/slugma/front.dimensions\
	gfx/pokemon/smeargle/front.dimensions\
	gfx/pokemon/smoochum/front.dimensions\
	gfx/pokemon/sneasel/front.dimensions\
	gfx/pokemon/snorlax/front.dimensions\
	gfx/pokemon/snubbull/front.dimensions\
	gfx/pokemon/spearow/front.dimensions\
	gfx/pokemon/spinarak/front.dimensions\
	gfx/pokemon/squirtle/front.dimensions\
	gfx/pokemon/stantler/front.dimensions\
	gfx/pokemon/starmie/front.dimensions\
	gfx/pokemon/staryu/front.dimensions\
	gfx/pokemon/steelix/front.dimensions\
	gfx/pokemon/sudowoodo/front.dimensions\
	gfx/pokemon/suicune/front.dimensions\
	gfx/pokemon/sunflora/front.dimensions\
	gfx/pokemon/sunkern/front.dimensions\
	gfx/pokemon/swinub/front.dimensions\
	gfx/pokemon/tangela/front.dimensions\
	gfx/pokemon/tauros/front.dimensions\
	gfx/pokemon/teddiursa/front.dimensions\
	gfx/pokemon/tentacool/front.dimensions\
	gfx/pokemon/tentacruel/front.dimensions\
	gfx/pokemon/togepi/front.dimensions\
	gfx/pokemon/togetic/front.dimensions\
	gfx/pokemon/totodile/front.dimensions\
	gfx/pokemon/typhlosion/front.dimensions\
	gfx/pokemon/tyranitar/front.dimensions\
	gfx/pokemon/tyrogue/front.dimensions\
	gfx/pokemon/umbreon/front.dimensions\
	gfx/pokemon/unown_a/front.dimensions\
	gfx/pokemon/ursaring/front.dimensions\
	gfx/pokemon/vaporeon/front.dimensions\
	gfx/pokemon/venomoth/front.dimensions\
	gfx/pokemon/venonat/front.dimensions\
	gfx/pokemon/venusaur/front.dimensions\
	gfx/pokemon/victreebel/front.dimensions\
	gfx/pokemon/vileplume/front.dimensions\
	gfx/pokemon/voltorb/front.dimensions\
	gfx/pokemon/vulpix/front.dimensions\
	gfx/pokemon/wartortle/front.dimensions\
	gfx/pokemon/weedle/front.dimensions\
	gfx/pokemon/weepinbell/front.dimensions\
	gfx/pokemon/weezing/front.dimensions\
	gfx/pokemon/wigglytuff/front.dimensions\
	gfx/pokemon/wobbuffet/front.dimensions\
	gfx/pokemon/wooper/front.dimensions\
	gfx/pokemon/xatu/front.dimensions\
	gfx/pokemon/yanma/front.dimensions\
	gfx/pokemon/zapdos/front.dimensions\
	gfx/pokemon/zubat/front.dimensions\

PALFILES=\
	gfx/pokemon/bulbasaur/front.gbcpal\
	gfx/pokemon/ivysaur/front.gbcpal\
	gfx/pokemon/venusaur/front.gbcpal\
	gfx/pokemon/charmander/front.gbcpal\
	gfx/pokemon/charmeleon/front.gbcpal\
	gfx/pokemon/charizard/front.gbcpal\
	gfx/pokemon/squirtle/front.gbcpal\
	gfx/pokemon/wartortle/front.gbcpal\
	gfx/pokemon/blastoise/front.gbcpal\
	gfx/pokemon/caterpie/front.gbcpal\
	gfx/pokemon/metapod/front.gbcpal\
	gfx/pokemon/butterfree/front.gbcpal\
	gfx/pokemon/weedle/front.gbcpal\
	gfx/pokemon/kakuna/front.gbcpal\
	gfx/pokemon/beedrill/front.gbcpal\
	gfx/pokemon/pidgey/front.gbcpal\
	gfx/pokemon/pidgeotto/front.gbcpal\
	gfx/pokemon/pidgeot/front.gbcpal\
	gfx/pokemon/rattata/front.gbcpal\
	gfx/pokemon/raticate/front.gbcpal\
	gfx/pokemon/spearow/front.gbcpal\
	gfx/pokemon/fearow/front.gbcpal\
	gfx/pokemon/ekans/front.gbcpal\
	gfx/pokemon/arbok/front.gbcpal\
	gfx/pokemon/pikachu/front.gbcpal\
	gfx/pokemon/raichu/front.gbcpal\
	gfx/pokemon/sandshrew/front.gbcpal\
	gfx/pokemon/sandslash/front.gbcpal\
	gfx/pokemon/nidoran_f/front.gbcpal\
	gfx/pokemon/nidorina/front.gbcpal\
	gfx/pokemon/nidoqueen/front.gbcpal\
	gfx/pokemon/nidoran_m/front.gbcpal\
	gfx/pokemon/nidorino/front.gbcpal\
	gfx/pokemon/nidoking/front.gbcpal\
	gfx/pokemon/clefairy/front.gbcpal\
	gfx/pokemon/clefable/front.gbcpal\
	gfx/pokemon/vulpix/front.gbcpal\
	gfx/pokemon/ninetales/front.gbcpal\
	gfx/pokemon/jigglypuff/front.gbcpal\
	gfx/pokemon/wigglytuff/front.gbcpal\
	gfx/pokemon/zubat/front.gbcpal\
	gfx/pokemon/golbat/front.gbcpal\
	gfx/pokemon/oddish/front.gbcpal\
	gfx/pokemon/gloom/front.gbcpal\
	gfx/pokemon/vileplume/front.gbcpal\
	gfx/pokemon/paras/front.gbcpal\
	gfx/pokemon/parasect/front.gbcpal\
	gfx/pokemon/venonat/front.gbcpal\
	gfx/pokemon/venomoth/front.gbcpal\
	gfx/pokemon/diglett/front.gbcpal\
	gfx/pokemon/dugtrio/front.gbcpal\
	gfx/pokemon/meowth/front.gbcpal\
	gfx/pokemon/persian/front.gbcpal\
	gfx/pokemon/psyduck/front.gbcpal\
	gfx/pokemon/golduck/front.gbcpal\
	gfx/pokemon/mankey/front.gbcpal\
	gfx/pokemon/primeape/front.gbcpal\
	gfx/pokemon/growlithe/front.gbcpal\
	gfx/pokemon/arcanine/front.gbcpal\
	gfx/pokemon/poliwag/front.gbcpal\
	gfx/pokemon/poliwhirl/front.gbcpal\
	gfx/pokemon/poliwrath/front.gbcpal\
	gfx/pokemon/abra/front.gbcpal\
	gfx/pokemon/kadabra/front.gbcpal\
	gfx/pokemon/alakazam/front.gbcpal\
	gfx/pokemon/machop/front.gbcpal\
	gfx/pokemon/machoke/front.gbcpal\
	gfx/pokemon/machamp/front.gbcpal\
	gfx/pokemon/bellsprout/front.gbcpal\
	gfx/pokemon/weepinbell/front.gbcpal\
	gfx/pokemon/victreebel/front.gbcpal\
	gfx/pokemon/tentacool/front.gbcpal\
	gfx/pokemon/tentacruel/front.gbcpal\
	gfx/pokemon/geodude/front.gbcpal\
	gfx/pokemon/graveler/front.gbcpal\
	gfx/pokemon/golem/front.gbcpal\
	gfx/pokemon/ponyta/front.gbcpal\
	gfx/pokemon/rapidash/front.gbcpal\
	gfx/pokemon/slowpoke/front.gbcpal\
	gfx/pokemon/slowbro/front.gbcpal\
	gfx/pokemon/magnemite/front.gbcpal\
	gfx/pokemon/magneton/front.gbcpal\
	gfx/pokemon/farfetch_d/front.gbcpal\
	gfx/pokemon/doduo/front.gbcpal\
	gfx/pokemon/dodrio/front.gbcpal\
	gfx/pokemon/seel/front.gbcpal\
	gfx/pokemon/dewgong/front.gbcpal\
	gfx/pokemon/grimer/front.gbcpal\
	gfx/pokemon/muk/front.gbcpal\
	gfx/pokemon/shellder/front.gbcpal\
	gfx/pokemon/cloyster/front.gbcpal\
	gfx/pokemon/gastly/front.gbcpal\
	gfx/pokemon/haunter/front.gbcpal\
	gfx/pokemon/gengar/front.gbcpal\
	gfx/pokemon/onix/front.gbcpal\
	gfx/pokemon/drowzee/front.gbcpal\
	gfx/pokemon/hypno/front.gbcpal\
	gfx/pokemon/krabby/front.gbcpal\
	gfx/pokemon/kingler/front.gbcpal\
	gfx/pokemon/voltorb/front.gbcpal\
	gfx/pokemon/electrode/front.gbcpal\
	gfx/pokemon/exeggcute/front.gbcpal\
	gfx/pokemon/exeggutor/front.gbcpal\
	gfx/pokemon/cubone/front.gbcpal\
	gfx/pokemon/marowak/front.gbcpal\
	gfx/pokemon/hitmonlee/front.gbcpal\
	gfx/pokemon/hitmonchan/front.gbcpal\
	gfx/pokemon/lickitung/front.gbcpal\
	gfx/pokemon/koffing/front.gbcpal\
	gfx/pokemon/weezing/front.gbcpal\
	gfx/pokemon/rhyhorn/front.gbcpal\
	gfx/pokemon/rhydon/front.gbcpal\
	gfx/pokemon/chansey/front.gbcpal\
	gfx/pokemon/tangela/front.gbcpal\
	gfx/pokemon/kangaskhan/front.gbcpal\
	gfx/pokemon/horsea/front.gbcpal\
	gfx/pokemon/seadra/front.gbcpal\
	gfx/pokemon/goldeen/front.gbcpal\
	gfx/pokemon/seaking/front.gbcpal\
	gfx/pokemon/staryu/front.gbcpal\
	gfx/pokemon/starmie/front.gbcpal\
	gfx/pokemon/mr__mime/front.gbcpal\
	gfx/pokemon/scyther/front.gbcpal\
	gfx/pokemon/jynx/front.gbcpal\
	gfx/pokemon/electabuzz/front.gbcpal\
	gfx/pokemon/magmar/front.gbcpal\
	gfx/pokemon/pinsir/front.gbcpal\
	gfx/pokemon/tauros/front.gbcpal\
	gfx/pokemon/magikarp/front.gbcpal\
	gfx/pokemon/gyarados/front.gbcpal\
	gfx/pokemon/lapras/front.gbcpal\
	gfx/pokemon/ditto/front.gbcpal\
	gfx/pokemon/eevee/front.gbcpal\
	gfx/pokemon/vaporeon/front.gbcpal\
	gfx/pokemon/jolteon/front.gbcpal\
	gfx/pokemon/flareon/front.gbcpal\
	gfx/pokemon/porygon/front.gbcpal\
	gfx/pokemon/omanyte/front.gbcpal\
	gfx/pokemon/omastar/front.gbcpal\
	gfx/pokemon/kabuto/front.gbcpal\
	gfx/pokemon/kabutops/front.gbcpal\
	gfx/pokemon/aerodactyl/front.gbcpal\
	gfx/pokemon/snorlax/front.gbcpal\
	gfx/pokemon/articuno/front.gbcpal\
	gfx/pokemon/zapdos/front.gbcpal\
	gfx/pokemon/moltres/front.gbcpal\
	gfx/pokemon/dratini/front.gbcpal\
	gfx/pokemon/dragonair/front.gbcpal\
	gfx/pokemon/dragonite/front.gbcpal\
	gfx/pokemon/mewtwo/front.gbcpal\
	gfx/pokemon/mew/front.gbcpal\
	gfx/pokemon/chikorita/front.gbcpal\
	gfx/pokemon/bayleef/front.gbcpal\
	gfx/pokemon/meganium/front.gbcpal\
	gfx/pokemon/cyndaquil/front.gbcpal\
	gfx/pokemon/quilava/front.gbcpal\
	gfx/pokemon/typhlosion/front.gbcpal\
	gfx/pokemon/totodile/front.gbcpal\
	gfx/pokemon/croconaw/front.gbcpal\
	gfx/pokemon/feraligatr/front.gbcpal\
	gfx/pokemon/sentret/front.gbcpal\
	gfx/pokemon/furret/front.gbcpal\
	gfx/pokemon/hoothoot/front.gbcpal\
	gfx/pokemon/noctowl/front.gbcpal\
	gfx/pokemon/ledyba/front.gbcpal\
	gfx/pokemon/ledian/front.gbcpal\
	gfx/pokemon/spinarak/front.gbcpal\
	gfx/pokemon/ariados/front.gbcpal\
	gfx/pokemon/crobat/front.gbcpal\
	gfx/pokemon/chinchou/front.gbcpal\
	gfx/pokemon/lanturn/front.gbcpal\
	gfx/pokemon/pichu/front.gbcpal\
	gfx/pokemon/cleffa/front.gbcpal\
	gfx/pokemon/igglybuff/front.gbcpal\
	gfx/pokemon/togepi/front.gbcpal\
	gfx/pokemon/togetic/front.gbcpal\
	gfx/pokemon/natu/front.gbcpal\
	gfx/pokemon/xatu/front.gbcpal\
	gfx/pokemon/mareep/front.gbcpal\
	gfx/pokemon/flaaffy/front.gbcpal\
	gfx/pokemon/ampharos/front.gbcpal\
	gfx/pokemon/bellossom/front.gbcpal\
	gfx/pokemon/marill/front.gbcpal\
	gfx/pokemon/azumarill/front.gbcpal\
	gfx/pokemon/sudowoodo/front.gbcpal\
	gfx/pokemon/politoed/front.gbcpal\
	gfx/pokemon/hoppip/front.gbcpal\
	gfx/pokemon/skiploom/front.gbcpal\
	gfx/pokemon/jumpluff/front.gbcpal\
	gfx/pokemon/aipom/front.gbcpal\
	gfx/pokemon/sunkern/front.gbcpal\
	gfx/pokemon/sunflora/front.gbcpal\
	gfx/pokemon/yanma/front.gbcpal\
	gfx/pokemon/wooper/front.gbcpal\
	gfx/pokemon/quagsire/front.gbcpal\
	gfx/pokemon/espeon/front.gbcpal\
	gfx/pokemon/umbreon/front.gbcpal\
	gfx/pokemon/murkrow/front.gbcpal\
	gfx/pokemon/slowking/front.gbcpal\
	gfx/pokemon/misdreavus/front.gbcpal\
	gfx/pokemon/wobbuffet/front.gbcpal\
	gfx/pokemon/girafarig/front.gbcpal\
	gfx/pokemon/pineco/front.gbcpal\
	gfx/pokemon/forretress/front.gbcpal\
	gfx/pokemon/dunsparce/front.gbcpal\
	gfx/pokemon/gligar/front.gbcpal\
	gfx/pokemon/steelix/front.gbcpal\
	gfx/pokemon/snubbull/front.gbcpal\
	gfx/pokemon/granbull/front.gbcpal\
	gfx/pokemon/qwilfish/front.gbcpal\
	gfx/pokemon/scizor/front.gbcpal\
	gfx/pokemon/shuckle/front.gbcpal\
	gfx/pokemon/heracross/front.gbcpal\
	gfx/pokemon/sneasel/front.gbcpal\
	gfx/pokemon/teddiursa/front.gbcpal\
	gfx/pokemon/ursaring/front.gbcpal\
	gfx/pokemon/slugma/front.gbcpal\
	gfx/pokemon/magcargo/front.gbcpal\
	gfx/pokemon/swinub/front.gbcpal\
	gfx/pokemon/piloswine/front.gbcpal\
	gfx/pokemon/corsola/front.gbcpal\
	gfx/pokemon/remoraid/front.gbcpal\
	gfx/pokemon/octillery/front.gbcpal\
	gfx/pokemon/delibird/front.gbcpal\
	gfx/pokemon/mantine/front.gbcpal\
	gfx/pokemon/skarmory/front.gbcpal\
	gfx/pokemon/houndour/front.gbcpal\
	gfx/pokemon/houndoom/front.gbcpal\
	gfx/pokemon/kingdra/front.gbcpal\
	gfx/pokemon/phanpy/front.gbcpal\
	gfx/pokemon/donphan/front.gbcpal\
	gfx/pokemon/porygon2/front.gbcpal\
	gfx/pokemon/stantler/front.gbcpal\
	gfx/pokemon/smeargle/front.gbcpal\
	gfx/pokemon/tyrogue/front.gbcpal\
	gfx/pokemon/hitmontop/front.gbcpal\
	gfx/pokemon/smoochum/front.gbcpal\
	gfx/pokemon/elekid/front.gbcpal\
	gfx/pokemon/magby/front.gbcpal\
	gfx/pokemon/miltank/front.gbcpal\
	gfx/pokemon/blissey/front.gbcpal\
	gfx/pokemon/raikou/front.gbcpal\
	gfx/pokemon/entei/front.gbcpal\
	gfx/pokemon/suicune/front.gbcpal\
	gfx/pokemon/larvitar/front.gbcpal\
	gfx/pokemon/pupitar/front.gbcpal\
	gfx/pokemon/tyranitar/front.gbcpal\
	gfx/pokemon/lugia/front.gbcpal\
	gfx/pokemon/ho_oh/front.gbcpal\
	gfx/pokemon/celebi/front.gbcpal\
	gfx/pokemon/egg/front.gbcpal\
	gfx/trainers/cal.gbcpal\
	gfx/trainers/falkner.gbcpal\
	gfx/trainers/whitney.gbcpal\
	gfx/trainers/bugsy.gbcpal\
	gfx/trainers/morty.gbcpal\
	gfx/trainers/pryce.gbcpal\
	gfx/trainers/jasmine.gbcpal\
	gfx/trainers/chuck.gbcpal\
	gfx/trainers/clair.gbcpal\
	gfx/trainers/rival1.gbcpal\
	gfx/trainers/oak.gbcpal\
	gfx/trainers/will.gbcpal\
	gfx/trainers/cal.gbcpal\
	gfx/trainers/bruno.gbcpal\
	gfx/trainers/karen.gbcpal\
	gfx/trainers/koga.gbcpal\
	gfx/trainers/champion.gbcpal\
	gfx/trainers/brock.gbcpal\
	gfx/trainers/misty.gbcpal\
	gfx/trainers/lt_surge.gbcpal\
	gfx/trainers/scientist.gbcpal\
	gfx/trainers/erika.gbcpal\
	gfx/trainers/youngster.gbcpal\
	gfx/trainers/schoolboy.gbcpal\
	gfx/trainers/bird_keeper.gbcpal\
	gfx/trainers/lass.gbcpal\
	gfx/trainers/janine.gbcpal\
	gfx/trainers/cooltrainer_m.gbcpal\
	gfx/trainers/cooltrainer_f.gbcpal\
	gfx/trainers/beauty.gbcpal\
	gfx/trainers/pokemaniac.gbcpal\
	gfx/trainers/grunt_m.gbcpal\
	gfx/trainers/gentleman.gbcpal\
	gfx/trainers/skier.gbcpal\
	gfx/trainers/teacher.gbcpal\
	gfx/trainers/sabrina.gbcpal\
	gfx/trainers/bug_catcher.gbcpal\
	gfx/trainers/fisher.gbcpal\
	gfx/trainers/swimmer_m.gbcpal\
	gfx/trainers/swimmer_f.gbcpal\
	gfx/trainers/sailor.gbcpal\
	gfx/trainers/super_nerd.gbcpal\
	gfx/trainers/rival2.gbcpal\
	gfx/trainers/guitarist.gbcpal\
	gfx/trainers/hiker.gbcpal\
	gfx/trainers/biker.gbcpal\
	gfx/trainers/blaine.gbcpal\
	gfx/trainers/burglar.gbcpal\
	gfx/trainers/firebreather.gbcpal\
	gfx/trainers/juggler.gbcpal\
	gfx/trainers/blackbelt_t.gbcpal\
	gfx/trainers/executive_m.gbcpal\
	gfx/trainers/psychic_t.gbcpal\
	gfx/trainers/picnicker.gbcpal\
	gfx/trainers/camper.gbcpal\
	gfx/trainers/executive_f.gbcpal\
	gfx/trainers/sage.gbcpal\
	gfx/trainers/medium.gbcpal\
	gfx/trainers/boarder.gbcpal\
	gfx/trainers/pokefan_m.gbcpal\
	gfx/trainers/kimono_girl.gbcpal\
	gfx/trainers/twins.gbcpal\
	gfx/trainers/pokefan_f.gbcpal\
	gfx/trainers/red.gbcpal\
	gfx/trainers/blue.gbcpal\
	gfx/trainers/officer.gbcpal\
	gfx/trainers/grunt_f.gbcpal\
	gfx/trainers/mysticalman.gbcpal\

LZFILES=\
	gfx/diploma/diploma.2bpp.lz\
	gfx/card_flip/card_flip_3.2bpp.lz\
	gfx/card_flip/card_flip_1.2bpp.lz\
	gfx/card_flip/card_flip_2.2bpp.lz\
	gfx/memory_game/memory_game.2bpp.lz\
	gfx/slots/slots_1.2bpp.lz\
	gfx/slots/slots_2.2bpp.lz\
	gfx/slots/slots_3.2bpp.lz\
	gfx/unown_puzzle/start_cancel.2bpp.lz\
	gfx/unown_puzzle/hooh.2bpp.lz\
	gfx/unown_puzzle/aerodactyl.2bpp.lz\
	gfx/unown_puzzle/kabuto.2bpp.lz\
	gfx/unown_puzzle/omanyte.2bpp.lz\
	gfx/sgb/gbc_only.2bpp.lz\
	gfx/intro/suicune_run.2bpp.lz\
	gfx/intro/pichu_wooper.2bpp.lz\
	gfx/intro/background.2bpp.lz\
	gfx/intro/background.tilemap.lz\
	gfx/intro/background.attrmap.lz\
	gfx/intro/unowns.2bpp.lz\
	gfx/intro/pulse.2bpp.lz\
	gfx/intro/unown_a.tilemap.lz\
	gfx/intro/unown_a.attrmap.lz\
	gfx/intro/unown_hi.tilemap.lz\
	gfx/intro/unown_hi.attrmap.lz\
	gfx/intro/unowns.tilemap.lz\
	gfx/intro/unowns.attrmap.lz\
	gfx/intro/crystal_unowns.2bpp.lz\
	gfx/intro/crystal_unowns.tilemap.lz\
	gfx/intro/crystal_unowns.attrmap.lz\
	gfx/intro/suicune_close.2bpp.lz\
	gfx/intro/suicune_close.tilemap.lz\
	gfx/intro/suicune_close.attrmap.lz\
	gfx/intro/suicune_jump.2bpp.lz\
	gfx/intro/suicune_back.2bpp.lz\
	gfx/intro/suicune_jump.tilemap.lz\
	gfx/intro/suicune_jump.attrmap.lz\
	gfx/intro/suicune_back.tilemap.lz\
	gfx/intro/suicune_back.attrmap.lz\
	gfx/intro/unown_back.2bpp.lz\
	gfx/title/suicune.2bpp.lz\
	gfx/title/logo.2bpp.lz\
	gfx/title/crystal.2bpp.lz\
	gfx/trade/game_boy_cable.2bpp.lz\
	gfx/pokedex/pokedex.2bpp.lz\
	gfx/pokedex/slowpoke.2bpp.lz\
	gfx/pokedex/pokedex_sgb.2bpp.lz\
	gfx/pokedex/question_mark.2bpp.lz\
	gfx/pokegear/pokegear_sprites.2bpp.lz\
	gfx/pc/pc.2bpp.lz\
	gfx/battle_anims/hit.2bpp.lz\
	gfx/battle_anims/cut.2bpp.lz\
	gfx/battle_anims/fire.2bpp.lz\
	gfx/battle_anims/water.2bpp.lz\
	gfx/battle_anims/lightning.2bpp.lz\
	gfx/battle_anims/smoke.2bpp.lz\
	gfx/battle_anims/explosion.2bpp.lz\
	gfx/battle_anims/ice.2bpp.lz\
	gfx/battle_anims/rocks.2bpp.lz\
	gfx/battle_anims/poison.2bpp.lz\
	gfx/battle_anims/plant.2bpp.lz\
	gfx/battle_anims/pokeball.2bpp.lz\
	gfx/battle_anims/bubble.2bpp.lz\
	gfx/battle_anims/noise.2bpp.lz\
	gfx/battle_anims/reflect.2bpp.lz\
	gfx/battle_anims/powder.2bpp.lz\
	gfx/battle_anims/beam.2bpp.lz\
	gfx/battle_anims/speed.2bpp.lz\
	gfx/battle_anims/charge.2bpp.lz\
	gfx/battle_anims/wind.2bpp.lz\
	gfx/battle_anims/whip.2bpp.lz\
	gfx/battle_anims/rope.2bpp.lz\
	gfx/battle_anims/egg.2bpp.lz\
	gfx/battle_anims/psychic.2bpp.lz\
	gfx/battle_anims/sand.2bpp.lz\
	gfx/battle_anims/web.2bpp.lz\
	gfx/battle_anims/haze.2bpp.lz\
	gfx/battle_anims/horn.2bpp.lz\
	gfx/battle_anims/flower.2bpp.lz\
	gfx/battle_anims/misc.2bpp.lz\
	gfx/battle_anims/skyattack.2bpp.lz\
	gfx/battle_anims/globe.2bpp.lz\
	gfx/battle_anims/shapes.2bpp.lz\
	gfx/battle_anims/status.2bpp.lz\
	gfx/battle_anims/objects.2bpp.lz\
	gfx/battle_anims/shine.2bpp.lz\
	gfx/battle_anims/angels.2bpp.lz\
	gfx/battle_anims/wave.2bpp.lz\
	gfx/battle_anims/aeroblast.2bpp.lz\
	gfx/pokegear/town_map.2bpp.lz\
	gfx/player/chris_back.2bpp.lz\
	gfx/battle/dude.2bpp.lz\
	gfx/new_game/shrink1.2bpp.lz\
	gfx/new_game/shrink2.2bpp.lz\
	gfx/pokemon/egg/unused_front.2bpp.lz\
	gfx/splash/ditto.2bpp.lz\
	gfx/pokegear/pokegear.2bpp.lz\
	gfx/pokemon/ho_oh/front.animated.2bpp.lz\
	gfx/pokemon/machamp/front.animated.2bpp.lz\
	gfx/pokemon/ninetales/front.animated.2bpp.lz\
	gfx/pokemon/feraligatr/front.animated.2bpp.lz\
	gfx/pokemon/nidoking/front.animated.2bpp.lz\
	gfx/pokemon/raikou/front.animated.2bpp.lz\
	gfx/pokemon/lugia/front.animated.2bpp.lz\
	gfx/pokemon/articuno/front.animated.2bpp.lz\
	gfx/pokemon/tauros/front.animated.2bpp.lz\
	gfx/pokemon/venusaur/front.animated.2bpp.lz\
	gfx/pokemon/entei/front.animated.2bpp.lz\
	gfx/pokemon/suicune/front.animated.2bpp.lz\
	gfx/pokemon/typhlosion/front.animated.2bpp.lz\
	gfx/pokemon/blastoise/front.animated.2bpp.lz\
	gfx/pokemon/rapidash/front.animated.2bpp.lz\
	gfx/pokemon/meganium/front.animated.2bpp.lz\
	gfx/pokemon/nidoqueen/front.animated.2bpp.lz\
	gfx/pokemon/hitmonlee/front.animated.2bpp.lz\
	gfx/pokemon/scizor/front.animated.2bpp.lz\
	gfx/pokemon/beedrill/front.animated.2bpp.lz\
	gfx/pokemon/arcanine/front.animated.2bpp.lz\
	gfx/pokemon/tyranitar/front.animated.2bpp.lz\
	gfx/pokemon/moltres/front.animated.2bpp.lz\
	gfx/pokemon/zapdos/front.animated.2bpp.lz\
	gfx/pokemon/arbok/front.animated.2bpp.lz\
	gfx/pokemon/mewtwo/front.animated.2bpp.lz\
	gfx/pokemon/fearow/front.animated.2bpp.lz\
	gfx/pokemon/charizard/front.animated.2bpp.lz\
	gfx/pokemon/quilava/front.animated.2bpp.lz\
	gfx/pokemon/steelix/front.animated.2bpp.lz\
	gfx/pokemon/alakazam/front.animated.2bpp.lz\
	gfx/pokemon/gyarados/front.animated.2bpp.lz\
	gfx/pokemon/kangaskhan/front.animated.2bpp.lz\
	gfx/pokemon/rhydon/front.animated.2bpp.lz\
	gfx/pokemon/golduck/front.animated.2bpp.lz\
	gfx/pokemon/rhyhorn/front.animated.2bpp.lz\
	gfx/pokemon/pidgeot/front.animated.2bpp.lz\
	gfx/pokemon/slowbro/front.animated.2bpp.lz\
	gfx/pokemon/butterfree/front.animated.2bpp.lz\
	gfx/pokemon/weezing/front.animated.2bpp.lz\
	gfx/pokemon/cloyster/front.animated.2bpp.lz\
	gfx/pokemon/skarmory/front.animated.2bpp.lz\
	gfx/pokemon/dewgong/front.animated.2bpp.lz\
	gfx/pokemon/victreebel/front.animated.2bpp.lz\
	gfx/pokemon/raichu/front.animated.2bpp.lz\
	gfx/pokemon/primeape/front.animated.2bpp.lz\
	gfx/pokemon/omastar/back.2bpp.lz\
	gfx/pokemon/dodrio/front.animated.2bpp.lz\
	gfx/pokemon/slowking/front.animated.2bpp.lz\
	gfx/pokemon/hitmontop/front.animated.2bpp.lz\
	gfx/pokemon/onix/front.animated.2bpp.lz\
	gfx/pokemon/blissey/front.animated.2bpp.lz\
	gfx/pokemon/machoke/front.animated.2bpp.lz\
	gfx/pokemon/dragonite/front.animated.2bpp.lz\
	gfx/pokemon/poliwrath/front.animated.2bpp.lz\
	gfx/pokemon/scyther/front.animated.2bpp.lz\
	gfx/pokemon/aerodactyl/front.animated.2bpp.lz\
	gfx/pokemon/seaking/front.animated.2bpp.lz\
	gfx/pokemon/muk/front.animated.2bpp.lz\
	gfx/pokemon/croconaw/front.animated.2bpp.lz\
	gfx/pokemon/hypno/front.animated.2bpp.lz\
	gfx/pokemon/nidorino/front.animated.2bpp.lz\
	gfx/pokemon/sandslash/front.animated.2bpp.lz\
	gfx/pokemon/jolteon/front.animated.2bpp.lz\
	gfx/pokemon/donphan/front.animated.2bpp.lz\
	gfx/pokemon/pinsir/front.animated.2bpp.lz\
	gfx/pokemon/unown_e/front.animated.2bpp.lz\
	gfx/pokemon/golbat/front.animated.2bpp.lz\
	gfx/pokemon/kingler/front.animated.2bpp.lz\
	gfx/pokemon/exeggcute/front.animated.2bpp.lz\
	gfx/pokemon/magcargo/front.animated.2bpp.lz\
	gfx/pokemon/persian/front.animated.2bpp.lz\
	gfx/pokemon/stantler/front.animated.2bpp.lz\
	gfx/pokemon/raticate/front.animated.2bpp.lz\
	gfx/pokemon/venomoth/front.animated.2bpp.lz\
	gfx/pokemon/politoed/front.animated.2bpp.lz\
	gfx/pokemon/electabuzz/front.animated.2bpp.lz\
	gfx/pokemon/mantine/front.animated.2bpp.lz\
	gfx/pokemon/lickitung/front.animated.2bpp.lz\
	gfx/pokemon/kingdra/front.animated.2bpp.lz\
	gfx/pokemon/charmeleon/front.animated.2bpp.lz\
	gfx/pokemon/kadabra/front.animated.2bpp.lz\
	gfx/pokemon/exeggutor/front.animated.2bpp.lz\
	gfx/pokemon/gastly/front.animated.2bpp.lz\
	gfx/pokemon/azumarill/front.animated.2bpp.lz\
	gfx/pokemon/parasect/front.animated.2bpp.lz\
	gfx/pokemon/mr__mime/front.animated.2bpp.lz\
	gfx/pokemon/heracross/front.animated.2bpp.lz\
	gfx/pokemon/ariados/front.animated.2bpp.lz\
	gfx/pokemon/noctowl/front.animated.2bpp.lz\
	gfx/pokemon/wartortle/front.animated.2bpp.lz\
	gfx/pokemon/lapras/front.animated.2bpp.lz\
	gfx/pokemon/golem/front.animated.2bpp.lz\
	gfx/pokemon/poliwhirl/front.animated.2bpp.lz\
	gfx/pokemon/ursaring/front.animated.2bpp.lz\
	gfx/pokemon/houndoom/front.animated.2bpp.lz\
	gfx/pokemon/kabutops/front.animated.2bpp.lz\
	gfx/pokemon/ampharos/front.animated.2bpp.lz\
	gfx/pokemon/nidorina/front.animated.2bpp.lz\
	gfx/pokemon/flareon/front.animated.2bpp.lz\
	gfx/pokemon/farfetch_d/front.animated.2bpp.lz\
	gfx/pokemon/vileplume/front.animated.2bpp.lz\
	gfx/pokemon/bayleef/front.animated.2bpp.lz\
	gfx/pokemon/magmar/front.animated.2bpp.lz\
	gfx/pokemon/tentacruel/front.animated.2bpp.lz\
	gfx/pokemon/elekid/front.animated.2bpp.lz\
	gfx/pokemon/jumpluff/front.animated.2bpp.lz\
	gfx/pokemon/marowak/front.animated.2bpp.lz\
	gfx/pokemon/vulpix/front.animated.2bpp.lz\
	gfx/pokemon/gligar/front.animated.2bpp.lz\
	gfx/pokemon/dunsparce/front.animated.2bpp.lz\
	gfx/pokemon/vaporeon/front.animated.2bpp.lz\
	gfx/pokemon/girafarig/front.animated.2bpp.lz\
	gfx/pokemon/drowzee/front.animated.2bpp.lz\
	gfx/pokemon/sneasel/front.animated.2bpp.lz\
	gfx/pokemon/bellossom/front.animated.2bpp.lz\
	gfx/pokemon/snorlax/front.animated.2bpp.lz\
	gfx/pokemon/wigglytuff/front.animated.2bpp.lz\
	gfx/pokemon/yanma/front.animated.2bpp.lz\
	gfx/pokemon/smeargle/front.animated.2bpp.lz\
	gfx/pokemon/clefable/front.animated.2bpp.lz\
	gfx/pokemon/ponyta/front.animated.2bpp.lz\
	gfx/pokemon/murkrow/front.animated.2bpp.lz\
	gfx/pokemon/graveler/front.animated.2bpp.lz\
	gfx/pokemon/starmie/front.animated.2bpp.lz\
	gfx/pokemon/pidgeotto/front.animated.2bpp.lz\
	gfx/pokemon/ledyba/front.animated.2bpp.lz\
	gfx/pokemon/gengar/front.animated.2bpp.lz\
	gfx/pokemon/omastar/front.animated.2bpp.lz\
	gfx/pokemon/piloswine/front.animated.2bpp.lz\
	gfx/pokemon/dugtrio/front.animated.2bpp.lz\
	gfx/pokemon/magneton/front.animated.2bpp.lz\
	gfx/pokemon/dragonair/front.animated.2bpp.lz\
	gfx/pokemon/forretress/front.animated.2bpp.lz\
	gfx/pokemon/togetic/front.animated.2bpp.lz\
	gfx/pokemon/kangaskhan/back.2bpp.lz\
	gfx/pokemon/seel/front.animated.2bpp.lz\
	gfx/pokemon/crobat/front.animated.2bpp.lz\
	gfx/pokemon/chansey/front.animated.2bpp.lz\
	gfx/pokemon/tangela/front.animated.2bpp.lz\
	gfx/pokemon/snubbull/front.animated.2bpp.lz\
	gfx/pokemon/granbull/front.animated.2bpp.lz\
	gfx/pokemon/miltank/front.animated.2bpp.lz\
	gfx/pokemon/haunter/front.animated.2bpp.lz\
	gfx/pokemon/sunflora/front.animated.2bpp.lz\
	gfx/pokemon/umbreon/front.animated.2bpp.lz\
	gfx/pokemon/chikorita/front.animated.2bpp.lz\
	gfx/pokemon/goldeen/front.animated.2bpp.lz\
	gfx/pokemon/espeon/front.animated.2bpp.lz\
	gfx/pokemon/xatu/front.animated.2bpp.lz\
	gfx/pokemon/mew/front.animated.2bpp.lz\
	gfx/pokemon/octillery/front.animated.2bpp.lz\
	gfx/pokemon/jynx/front.animated.2bpp.lz\
	gfx/pokemon/wobbuffet/front.animated.2bpp.lz\
	gfx/pokemon/delibird/front.animated.2bpp.lz\
	gfx/pokemon/ledian/front.animated.2bpp.lz\
	gfx/pokemon/gloom/front.animated.2bpp.lz\
	gfx/pokemon/flaaffy/front.animated.2bpp.lz\
	gfx/pokemon/ivysaur/front.animated.2bpp.lz\
	gfx/pokemon/furret/front.animated.2bpp.lz\
	gfx/pokemon/cyndaquil/front.animated.2bpp.lz\
	gfx/pokemon/hitmonchan/front.animated.2bpp.lz\
	gfx/pokemon/quagsire/front.animated.2bpp.lz\
	gfx/pokemon/ekans/front.animated.2bpp.lz\
	gfx/pokemon/sudowoodo/front.animated.2bpp.lz\
	gfx/pokemon/pikachu/front.animated.2bpp.lz\
	gfx/pokemon/seadra/front.animated.2bpp.lz\
	gfx/pokemon/magby/front.animated.2bpp.lz\
	gfx/pokemon/weepinbell/front.animated.2bpp.lz\
	gfx/pokemon/totodile/front.animated.2bpp.lz\
	gfx/pokemon/corsola/front.animated.2bpp.lz\
	gfx/trainers/firebreather.2bpp.lz\
	gfx/pokemon/machop/front.animated.2bpp.lz\
	gfx/pokemon/chinchou/front.animated.2bpp.lz\
	gfx/pokemon/rattata/front.animated.2bpp.lz\
	gfx/trainers/champion.2bpp.lz\
	gfx/pokemon/spearow/front.animated.2bpp.lz\
	gfx/pokemon/magikarp/front.animated.2bpp.lz\
	gfx/pokemon/charmander/front.animated.2bpp.lz\
	gfx/pokemon/cubone/front.animated.2bpp.lz\
	gfx/trainers/blackbelt_t.2bpp.lz\
	gfx/trainers/biker.2bpp.lz\
	gfx/pokemon/nidoran_m/front.animated.2bpp.lz\
	gfx/pokemon/porygon/front.animated.2bpp.lz\
	gfx/trainers/bruno.2bpp.lz\
	gfx/pokemon/grimer/front.animated.2bpp.lz\
	gfx/pokemon/staryu/front.animated.2bpp.lz\
	gfx/trainers/hiker.2bpp.lz\
	gfx/pokemon/meowth/front.animated.2bpp.lz\
	gfx/pokemon/porygon2/front.animated.2bpp.lz\
	gfx/pokemon/sandshrew/front.animated.2bpp.lz\
	gfx/pokemon/nidoran_f/front.animated.2bpp.lz\
	gfx/pokemon/pidgey/front.animated.2bpp.lz\
	gfx/pokemon/parasect/back.2bpp.lz\
	gfx/pokemon/misdreavus/front.animated.2bpp.lz\
	gfx/pokemon/houndour/front.animated.2bpp.lz\
	gfx/pokemon/mankey/front.animated.2bpp.lz\
	gfx/pokemon/celebi/front.animated.2bpp.lz\
	gfx/trainers/medium.2bpp.lz\
	gfx/pokemon/pineco/front.animated.2bpp.lz\
	gfx/pokemon/krabby/front.animated.2bpp.lz\
	gfx/trainers/fisher.2bpp.lz\
	gfx/pokemon/jigglypuff/front.animated.2bpp.lz\
	gfx/pokemon/paras/front.animated.2bpp.lz\
	gfx/pokemon/nidoking/back.2bpp.lz\
	gfx/trainers/pokefan_m.2bpp.lz\
	gfx/trainers/boarder.2bpp.lz\
	gfx/pokemon/psyduck/front.animated.2bpp.lz\
	gfx/pokemon/squirtle/front.animated.2bpp.lz\
	gfx/pokemon/machamp/back.2bpp.lz\
	gfx/pokemon/koffing/front.animated.2bpp.lz\
	gfx/pokemon/venonat/front.animated.2bpp.lz\
	gfx/pokemon/exeggutor/back.2bpp.lz\
	gfx/pokemon/lanturn/front.animated.2bpp.lz\
	gfx/pokemon/tyrogue/front.animated.2bpp.lz\
	gfx/pokemon/skiploom/front.animated.2bpp.lz\
	gfx/pokemon/mareep/front.animated.2bpp.lz\
	gfx/trainers/chuck.2bpp.lz\
	gfx/pokemon/eevee/front.animated.2bpp.lz\
	gfx/pokemon/butterfree/back.2bpp.lz\
	gfx/pokemon/zubat/front.animated.2bpp.lz\
	gfx/trainers/kimono_girl.2bpp.lz\
	gfx/pokemon/alakazam/back.2bpp.lz\
	gfx/pokemon/aipom/front.animated.2bpp.lz\
	gfx/pokemon/abra/front.animated.2bpp.lz\
	gfx/pokemon/hitmontop/back.2bpp.lz\
	gfx/pokemon/cloyster/back.2bpp.lz\
	gfx/pokemon/hoothoot/front.animated.2bpp.lz\
	gfx/pokemon/unown_f/back.2bpp.lz\
	gfx/pokemon/dodrio/back.2bpp.lz\
	gfx/pokemon/clefairy/front.animated.2bpp.lz\
	gfx/pokemon/slugma/front.animated.2bpp.lz\
	gfx/pokemon/growlithe/front.animated.2bpp.lz\
	gfx/pokemon/slowpoke/front.animated.2bpp.lz\
	gfx/pokemon/smoochum/front.animated.2bpp.lz\
	gfx/trainers/juggler.2bpp.lz\
	gfx/pokemon/marill/front.animated.2bpp.lz\
	gfx/trainers/guitarist.2bpp.lz\
	gfx/trainers/pokefan_f.2bpp.lz\
	gfx/pokemon/venomoth/back.2bpp.lz\
	gfx/trainers/clair.2bpp.lz\
	gfx/trainers/pokemaniac.2bpp.lz\
	gfx/pokemon/omanyte/front.animated.2bpp.lz\
	gfx/trainers/skier.2bpp.lz\
	gfx/pokemon/pupitar/front.animated.2bpp.lz\
	gfx/pokemon/bellsprout/front.animated.2bpp.lz\
	gfx/pokemon/shellder/front.animated.2bpp.lz\
	gfx/pokemon/tentacool/front.animated.2bpp.lz\
	gfx/pokemon/cleffa/front.animated.2bpp.lz\
	gfx/pokemon/gyarados/back.2bpp.lz\
	gfx/pokemon/ninetales/back.2bpp.lz\
	gfx/pokemon/yanma/back.2bpp.lz\
	gfx/pokemon/pinsir/back.2bpp.lz\
	gfx/trainers/lass.2bpp.lz\
	gfx/pokemon/clefable/back.2bpp.lz\
	gfx/pokemon/doduo/front.animated.2bpp.lz\
	gfx/pokemon/feraligatr/back.2bpp.lz\
	gfx/pokemon/dratini/front.animated.2bpp.lz\
	gfx/pokemon/magneton/back.2bpp.lz\
	gfx/pokemon/qwilfish/front.animated.2bpp.lz\
	gfx/pokemon/suicune/back.2bpp.lz\
	gfx/pokemon/slowking/back.2bpp.lz\
	gfx/pokemon/elekid/back.2bpp.lz\
	gfx/pokemon/celebi/back.2bpp.lz\
	gfx/pokemon/krabby/back.2bpp.lz\
	gfx/trainers/bug_catcher.2bpp.lz\
	gfx/pokemon/snorlax/back.2bpp.lz\
	gfx/pokemon/venusaur/back.2bpp.lz\
	gfx/pokemon/moltres/back.2bpp.lz\
	gfx/pokemon/sunflora/back.2bpp.lz\
	gfx/pokemon/phanpy/front.animated.2bpp.lz\
	gfx/pokemon/rhydon/back.2bpp.lz\
	gfx/pokemon/larvitar/front.animated.2bpp.lz\
	gfx/pokemon/tyranitar/back.2bpp.lz\
	gfx/pokemon/sandslash/back.2bpp.lz\
	gfx/pokemon/seadra/back.2bpp.lz\
	gfx/trainers/twins.2bpp.lz\
	gfx/pokemon/farfetch_d/back.2bpp.lz\
	gfx/pokemon/nidoran_m/back.2bpp.lz\
	gfx/pokemon/ledyba/back.2bpp.lz\
	gfx/pokemon/cyndaquil/back.2bpp.lz\
	gfx/pokemon/bayleef/back.2bpp.lz\
	gfx/pokemon/oddish/front.animated.2bpp.lz\
	gfx/pokemon/rapidash/back.2bpp.lz\
	gfx/pokemon/doduo/back.2bpp.lz\
	gfx/pokemon/hoppip/front.animated.2bpp.lz\
	gfx/pokemon/mankey/back.2bpp.lz\
	gfx/pokemon/magmar/back.2bpp.lz\
	gfx/pokemon/hypno/back.2bpp.lz\
	gfx/pokemon/quilava/back.2bpp.lz\
	gfx/pokemon/croconaw/back.2bpp.lz\
	gfx/pokemon/sandshrew/back.2bpp.lz\
	gfx/trainers/sailor.2bpp.lz\
	gfx/trainers/beauty.2bpp.lz\
	gfx/pokemon/shellder/back.2bpp.lz\
	gfx/pokemon/zubat/back.2bpp.lz\
	gfx/pokemon/teddiursa/front.animated.2bpp.lz\
	gfx/pokemon/cubone/back.2bpp.lz\
	gfx/trainers/grunt_m.2bpp.lz\
	gfx/pokemon/gloom/back.2bpp.lz\
	gfx/pokemon/magcargo/back.2bpp.lz\
	gfx/pokemon/kabutops/back.2bpp.lz\
	gfx/pokemon/beedrill/back.2bpp.lz\
	gfx/pokemon/arcanine/back.2bpp.lz\
	gfx/pokemon/flareon/back.2bpp.lz\
	gfx/pokemon/goldeen/back.2bpp.lz\
	gfx/pokemon/bulbasaur/front.animated.2bpp.lz\
	gfx/pokemon/starmie/back.2bpp.lz\
	gfx/pokemon/omanyte/back.2bpp.lz\
	gfx/pokemon/pidgey/back.2bpp.lz\
	gfx/trainers/scientist.2bpp.lz\
	gfx/pokemon/qwilfish/back.2bpp.lz\
	gfx/pokemon/gligar/back.2bpp.lz\
	gfx/pokemon/typhlosion/back.2bpp.lz\
	gfx/pokemon/charmeleon/back.2bpp.lz\
	gfx/pokemon/nidoqueen/back.2bpp.lz\
	gfx/pokemon/pichu/front.animated.2bpp.lz\
	gfx/pokemon/electabuzz/back.2bpp.lz\
	gfx/pokemon/ledian/back.2bpp.lz\
	gfx/pokemon/pupitar/back.2bpp.lz\
	gfx/pokemon/heracross/back.2bpp.lz\
	gfx/pokemon/unown_d/front.animated.2bpp.lz\
	gfx/pokemon/miltank/back.2bpp.lz\
	gfx/pokemon/steelix/back.2bpp.lz\
	gfx/pokemon/persian/back.2bpp.lz\
	gfx/trainers/lt_surge.2bpp.lz\
	gfx/trainers/teacher.2bpp.lz\
	gfx/pokemon/egg/front.animated.2bpp.lz\
	gfx/pokemon/eevee/back.2bpp.lz\
	gfx/pokemon/shuckle/front.animated.2bpp.lz\
	gfx/pokemon/ponyta/back.2bpp.lz\
	gfx/pokemon/remoraid/front.animated.2bpp.lz\
	gfx/pokemon/poliwag/front.animated.2bpp.lz\
	gfx/pokemon/onix/back.2bpp.lz\
	gfx/pokemon/koffing/back.2bpp.lz\
	gfx/trainers/bird_keeper.2bpp.lz\
	gfx/trainers/falkner.2bpp.lz\
	gfx/trainers/karen.2bpp.lz\
	gfx/pokemon/nidorina/back.2bpp.lz\
	gfx/pokemon/tentacruel/back.2bpp.lz\
	gfx/pokemon/growlithe/back.2bpp.lz\
	gfx/trainers/koga.2bpp.lz\
	gfx/pokemon/machoke/back.2bpp.lz\
	gfx/pokemon/raichu/back.2bpp.lz\
	gfx/pokemon/poliwrath/back.2bpp.lz\
	gfx/trainers/swimmer_m.2bpp.lz\
	gfx/pokemon/sunkern/front.animated.2bpp.lz\
	gfx/pokemon/nidorino/back.2bpp.lz\
	gfx/trainers/mysticalman.2bpp.lz\
	gfx/trainers/cooltrainer_f.2bpp.lz\
	gfx/pokemon/electrode/front.animated.2bpp.lz\
	gfx/pokemon/sudowoodo/back.2bpp.lz\
	gfx/pokemon/flaaffy/back.2bpp.lz\
	gfx/pokemon/sentret/front.animated.2bpp.lz\
	gfx/pokemon/togetic/back.2bpp.lz\
	gfx/trainers/bugsy.2bpp.lz\
	gfx/pokemon/marowak/back.2bpp.lz\
	gfx/pokemon/geodude/back.2bpp.lz\
	gfx/pokemon/scyther/back.2bpp.lz\
	gfx/pokemon/vileplume/back.2bpp.lz\
	gfx/pokemon/hitmonchan/back.2bpp.lz\
	gfx/pokemon/jumpluff/back.2bpp.lz\
	gfx/trainers/cooltrainer_m.2bpp.lz\
	gfx/pokemon/blastoise/back.2bpp.lz\
	gfx/pokemon/misdreavus/back.2bpp.lz\
	gfx/pokemon/tyrogue/back.2bpp.lz\
	gfx/pokemon/geodude/front.animated.2bpp.lz\
	gfx/pokemon/scizor/back.2bpp.lz\
	gfx/pokemon/girafarig/back.2bpp.lz\
	gfx/pokemon/stantler/back.2bpp.lz\
	gfx/pokemon/smeargle/back.2bpp.lz\
	gfx/pokemon/charizard/back.2bpp.lz\
	gfx/pokemon/kadabra/back.2bpp.lz\
	gfx/pokemon/primeape/back.2bpp.lz\
	gfx/pokemon/furret/back.2bpp.lz\
	gfx/pokemon/wartortle/back.2bpp.lz\
	gfx/pokemon/exeggcute/back.2bpp.lz\
	gfx/pokemon/igglybuff/front.animated.2bpp.lz\
	gfx/pokemon/raticate/back.2bpp.lz\
	gfx/pokemon/vulpix/back.2bpp.lz\
	gfx/pokemon/ekans/back.2bpp.lz\
	gfx/pokemon/seaking/back.2bpp.lz\
	gfx/trainers/burglar.2bpp.lz\
	gfx/pokemon/psyduck/back.2bpp.lz\
	gfx/pokemon/pikachu/back.2bpp.lz\
	gfx/pokemon/kabuto/front.animated.2bpp.lz\
	gfx/pokemon/mareep/back.2bpp.lz\
	gfx/pokemon/remoraid/back.2bpp.lz\
	gfx/pokemon/ditto/front.animated.2bpp.lz\
	gfx/pokemon/kingdra/back.2bpp.lz\
	gfx/trainers/camper.2bpp.lz\
	gfx/pokemon/wooper/front.animated.2bpp.lz\
	gfx/pokemon/clefairy/back.2bpp.lz\
	gfx/pokemon/venonat/back.2bpp.lz\
	gfx/pokemon/bellossom/back.2bpp.lz\
	gfx/trainers/rival1.2bpp.lz\
	gfx/pokemon/swinub/back.2bpp.lz\
	gfx/pokemon/mewtwo/back.2bpp.lz\
	gfx/trainers/oak.2bpp.lz\
	gfx/trainers/cal.2bpp.lz\
	gfx/trainers/swimmer_f.2bpp.lz\
	gfx/pokemon/diglett/front.animated.2bpp.lz\
	gfx/trainers/officer.2bpp.lz\
	gfx/pokemon/muk/back.2bpp.lz\
	gfx/pokemon/delibird/back.2bpp.lz\
	gfx/trainers/sabrina.2bpp.lz\
	gfx/pokemon/magikarp/back.2bpp.lz\
	gfx/pokemon/ariados/back.2bpp.lz\
	gfx/pokemon/sneasel/back.2bpp.lz\
	gfx/pokemon/umbreon/back.2bpp.lz\
	gfx/pokemon/murkrow/back.2bpp.lz\
	gfx/pokemon/ivysaur/back.2bpp.lz\
	gfx/pokemon/slowbro/back.2bpp.lz\
	gfx/trainers/psychic_t.2bpp.lz\
	gfx/pokemon/golduck/back.2bpp.lz\
	gfx/pokemon/weezing/back.2bpp.lz\
	gfx/pokemon/entei/back.2bpp.lz\
	gfx/trainers/grunt_f.2bpp.lz\
	gfx/pokemon/horsea/front.animated.2bpp.lz\
	gfx/pokemon/pidgeot/back.2bpp.lz\
	gfx/pokemon/ho_oh/back.2bpp.lz\
	gfx/pokemon/poliwhirl/back.2bpp.lz\
	gfx/pokemon/mew/back.2bpp.lz\
	gfx/pokemon/machop/back.2bpp.lz\
	gfx/pokemon/abra/back.2bpp.lz\
	gfx/pokemon/aerodactyl/back.2bpp.lz\
	gfx/pokemon/kakuna/front.animated.2bpp.lz\
	gfx/pokemon/dugtrio/back.2bpp.lz\
	gfx/pokemon/weepinbell/back.2bpp.lz\
	gfx/pokemon/nidoran_f/back.2bpp.lz\
	gfx/pokemon/graveler/back.2bpp.lz\
	gfx/pokemon/aipom/back.2bpp.lz\
	gfx/pokemon/espeon/back.2bpp.lz\
	gfx/pokemon/weedle/front.animated.2bpp.lz\
	gfx/pokemon/totodile/back.2bpp.lz\
	gfx/pokemon/snubbull/back.2bpp.lz\
	gfx/pokemon/kingler/back.2bpp.lz\
	gfx/pokemon/gengar/back.2bpp.lz\
	gfx/pokemon/rattata/back.2bpp.lz\
	gfx/trainers/youngster.2bpp.lz\
	gfx/trainers/will.2bpp.lz\
	gfx/trainers/schoolboy.2bpp.lz\
	gfx/pokemon/magnemite/front.animated.2bpp.lz\
	gfx/trainers/erika.2bpp.lz\
	gfx/trainers/janine.2bpp.lz\
	gfx/pokemon/magnemite/back.2bpp.lz\
	gfx/pokemon/hoothoot/back.2bpp.lz\
	gfx/pokemon/noctowl/back.2bpp.lz\
	gfx/trainers/morty.2bpp.lz\
	gfx/pokemon/slugma/back.2bpp.lz\
	gfx/pokemon/kabuto/back.2bpp.lz\
	gfx/pokemon/victreebel/back.2bpp.lz\
	gfx/pokemon/meowth/back.2bpp.lz\
	gfx/pokemon/meganium/back.2bpp.lz\
	gfx/trainers/picnicker.2bpp.lz\
	gfx/pokemon/lickitung/back.2bpp.lz\
	gfx/pokemon/togepi/front.animated.2bpp.lz\
	gfx/trainers/super_nerd.2bpp.lz\
	gfx/pokemon/haunter/back.2bpp.lz\
	gfx/pokemon/xatu/back.2bpp.lz\
	gfx/trainers/red.2bpp.lz\
	gfx/pokemon/porygon2/back.2bpp.lz\
	gfx/trainers/jasmine.2bpp.lz\
	gfx/pokemon/pineco/back.2bpp.lz\
	gfx/pokemon/metapod/front.animated.2bpp.lz\
	gfx/pokemon/seel/back.2bpp.lz\
	gfx/pokemon/quagsire/back.2bpp.lz\
	gfx/trainers/whitney.2bpp.lz\
	gfx/pokemon/jolteon/back.2bpp.lz\
	gfx/pokemon/caterpie/front.animated.2bpp.lz\
	gfx/pokemon/hoppip/back.2bpp.lz\
	gfx/trainers/blue.2bpp.lz\
	gfx/pokemon/granbull/back.2bpp.lz\
	gfx/trainers/gentleman.2bpp.lz\
	gfx/trainers/executive_m.2bpp.lz\
	gfx/pokemon/spearow/back.2bpp.lz\
	gfx/pokemon/sunkern/back.2bpp.lz\
	gfx/pokemon/lapras/back.2bpp.lz\
	gfx/pokemon/magby/back.2bpp.lz\
	gfx/pokemon/dragonair/back.2bpp.lz\
	gfx/pokemon/zapdos/back.2bpp.lz\
	gfx/pokemon/chikorita/back.2bpp.lz\
	gfx/pokemon/corsola/back.2bpp.lz\
	gfx/pokemon/chinchou/back.2bpp.lz\
	gfx/pokemon/chansey/back.2bpp.lz\
	gfx/pokemon/skiploom/back.2bpp.lz\
	gfx/pokemon/spinarak/front.animated.2bpp.lz\
	gfx/trainers/rival2.2bpp.lz\
	gfx/pokemon/unown_w/front.animated.2bpp.lz\
	gfx/pokemon/charmander/back.2bpp.lz\
	gfx/pokemon/rhyhorn/back.2bpp.lz\
	gfx/pokemon/unown_c/front.animated.2bpp.lz\
	gfx/trainers/misty.2bpp.lz\
	gfx/trainers/blaine.2bpp.lz\
	gfx/pokemon/unown_z/front.animated.2bpp.lz\
	gfx/pokemon/swinub/front.animated.2bpp.lz\
	gfx/pokemon/larvitar/back.2bpp.lz\
	gfx/pokemon/porygon/back.2bpp.lz\
	gfx/pokemon/unown_h/back.2bpp.lz\
	gfx/pokemon/paras/back.2bpp.lz\
	gfx/pokemon/vaporeon/back.2bpp.lz\
	gfx/pokemon/tentacool/back.2bpp.lz\
	gfx/trainers/executive_f.2bpp.lz\
	gfx/pokemon/bulbasaur/back.2bpp.lz\
	gfx/pokemon/smoochum/back.2bpp.lz\
	gfx/pokemon/pichu/back.2bpp.lz\
	gfx/pokemon/houndoom/back.2bpp.lz\
	gfx/pokemon/bellsprout/back.2bpp.lz\
	gfx/pokemon/grimer/back.2bpp.lz\
	gfx/pokemon/lanturn/back.2bpp.lz\
	gfx/pokemon/pidgeotto/back.2bpp.lz\
	gfx/pokemon/staryu/back.2bpp.lz\
	gfx/pokemon/mr__mime/back.2bpp.lz\
	gfx/pokemon/caterpie/back.2bpp.lz\
	gfx/pokemon/voltorb/front.animated.2bpp.lz\
	gfx/pokemon/lugia/back.2bpp.lz\
	gfx/trainers/pryce.2bpp.lz\
	gfx/trainers/brock.2bpp.lz\
	gfx/pokemon/unown_g/front.animated.2bpp.lz\
	gfx/pokemon/arbok/back.2bpp.lz\
	gfx/pokemon/politoed/back.2bpp.lz\
	gfx/pokemon/dragonite/back.2bpp.lz\
	gfx/pokemon/hitmonlee/back.2bpp.lz\
	gfx/pokemon/natu/front.animated.2bpp.lz\
	gfx/pokemon/ursaring/back.2bpp.lz\
	gfx/trainers/sage.2bpp.lz\
	gfx/pokemon/teddiursa/back.2bpp.lz\
	gfx/pokemon/phanpy/back.2bpp.lz\
	gfx/pokemon/unown_v/front.animated.2bpp.lz\
	gfx/pokemon/kakuna/back.2bpp.lz\
	gfx/pokemon/wobbuffet/back.2bpp.lz\
	gfx/pokemon/togepi/back.2bpp.lz\
	gfx/pokemon/crobat/back.2bpp.lz\
	gfx/pokemon/blissey/back.2bpp.lz\
	gfx/pokemon/ampharos/back.2bpp.lz\
	gfx/pokemon/igglybuff/back.2bpp.lz\
	gfx/pokemon/azumarill/back.2bpp.lz\
	gfx/pokemon/octillery/back.2bpp.lz\
	gfx/pokemon/unown_s/front.animated.2bpp.lz\
	gfx/pokemon/horsea/back.2bpp.lz\
	gfx/pokemon/sentret/back.2bpp.lz\
	gfx/pokemon/unown_o/front.animated.2bpp.lz\
	gfx/pokemon/unown_t/front.animated.2bpp.lz\
	gfx/pokemon/wigglytuff/back.2bpp.lz\
	gfx/pokemon/articuno/back.2bpp.lz\
	gfx/pokemon/ditto/back.2bpp.lz\
	gfx/pokemon/weedle/back.2bpp.lz\
	gfx/pokemon/unown_h/front.animated.2bpp.lz\
	gfx/pokemon/cleffa/back.2bpp.lz\
	gfx/pokemon/drowzee/back.2bpp.lz\
	gfx/pokemon/gastly/back.2bpp.lz\
	gfx/pokemon/fearow/back.2bpp.lz\
	gfx/pokemon/marill/back.2bpp.lz\
	gfx/pokemon/dratini/back.2bpp.lz\
	gfx/pokemon/electrode/back.2bpp.lz\
	gfx/pokemon/skarmory/back.2bpp.lz\
	gfx/pokemon/metapod/back.2bpp.lz\
	gfx/pokemon/jigglypuff/back.2bpp.lz\
	gfx/pokemon/oddish/back.2bpp.lz\
	gfx/pokemon/unown_d/back.2bpp.lz\
	gfx/pokemon/spinarak/back.2bpp.lz\
	gfx/pokemon/raikou/back.2bpp.lz\
	gfx/pokemon/unown_k/front.animated.2bpp.lz\
	gfx/pokemon/houndour/back.2bpp.lz\
	gfx/pokemon/poliwag/back.2bpp.lz\
	gfx/pokemon/squirtle/back.2bpp.lz\
	gfx/pokemon/shuckle/back.2bpp.lz\
	gfx/pokemon/dewgong/back.2bpp.lz\
	gfx/pokemon/unown_b/front.animated.2bpp.lz\
	gfx/pokemon/slowpoke/back.2bpp.lz\
	gfx/pokemon/dunsparce/back.2bpp.lz\
	gfx/pokemon/donphan/back.2bpp.lz\
	gfx/pokemon/wooper/back.2bpp.lz\
	gfx/pokemon/tauros/back.2bpp.lz\
	gfx/pokemon/unown_x/front.animated.2bpp.lz\
	gfx/pokemon/unown_n/front.animated.2bpp.lz\
	gfx/pokemon/tangela/back.2bpp.lz\
	gfx/pokemon/voltorb/back.2bpp.lz\
	gfx/pokemon/unown_j/front.animated.2bpp.lz\
	gfx/pokemon/mantine/back.2bpp.lz\
	gfx/pokemon/unown_l/front.animated.2bpp.lz\
	gfx/pokemon/piloswine/back.2bpp.lz\
	gfx/pokemon/unown_m/front.animated.2bpp.lz\
	gfx/pokemon/unown_f/front.animated.2bpp.lz\
	gfx/pokemon/natu/back.2bpp.lz\
	gfx/pokemon/unown_a/front.animated.2bpp.lz\
	gfx/pokemon/golem/back.2bpp.lz\
	gfx/pokemon/unown_u/front.animated.2bpp.lz\
	gfx/pokemon/diglett/back.2bpp.lz\
	gfx/pokemon/unown_q/front.animated.2bpp.lz\
	gfx/pokemon/unown_p/front.animated.2bpp.lz\
	gfx/pokemon/unown_c/back.2bpp.lz\
	gfx/pokemon/jynx/back.2bpp.lz\
	gfx/pokemon/golbat/back.2bpp.lz\
	gfx/pokemon/unown_y/front.animated.2bpp.lz\
	gfx/pokemon/unown_g/back.2bpp.lz\
	gfx/pokemon/unown_i/front.animated.2bpp.lz\
	gfx/pokemon/unown_v/back.2bpp.lz\
	gfx/pokemon/forretress/back.2bpp.lz\
	gfx/pokemon/unown_s/back.2bpp.lz\
	gfx/pokemon/unown_r/front.animated.2bpp.lz\
	gfx/pokemon/unown_e/back.2bpp.lz\
	gfx/pokemon/unown_j/back.2bpp.lz\
	gfx/pokemon/unown_b/back.2bpp.lz\
	gfx/pokemon/unown_o/back.2bpp.lz\
	gfx/pokemon/unown_z/back.2bpp.lz\
	gfx/pokemon/unown_w/back.2bpp.lz\
	gfx/pokemon/unown_n/back.2bpp.lz\
	gfx/pokemon/unown_a/back.2bpp.lz\
	gfx/pokemon/unown_m/back.2bpp.lz\
	gfx/pokemon/unown_k/back.2bpp.lz\
	gfx/pokemon/unown_t/back.2bpp.lz\
	gfx/pokemon/unown_x/back.2bpp.lz\
	gfx/pokemon/unown_l/back.2bpp.lz\
	gfx/pokemon/unown_u/back.2bpp.lz\
	gfx/pokemon/unown_q/back.2bpp.lz\
	gfx/pokemon/unown_y/back.2bpp.lz\
	gfx/pokemon/unown_p/back.2bpp.lz\
	gfx/pokemon/unown_i/back.2bpp.lz\
	gfx/pokemon/unown_r/back.2bpp.lz\
	gfx/pokemon/spinarak/back.2bpp.lz\
	gfx/pokemon/raikou/back.2bpp.lz\
	gfx/pokemon/unown_k/front.animated.2bpp.lz\
	gfx/pokemon/houndour/back.2bpp.lz\
	gfx/pokemon/poliwag/back.2bpp.lz\
	gfx/pokemon/squirtle/back.2bpp.lz\
	gfx/pokemon/shuckle/back.2bpp.lz\
	gfx/pokemon/dewgong/back.2bpp.lz\
	gfx/pokemon/unown_b/front.animated.2bpp.lz\
	gfx/pokemon/slowpoke/back.2bpp.lz\
	gfx/pokemon/dunsparce/back.2bpp.lz\
	gfx/pokemon/donphan/back.2bpp.lz\
	gfx/pokemon/wooper/back.2bpp.lz\
	gfx/pokemon/tauros/back.2bpp.lz\
	gfx/pokemon/unown_x/front.animated.2bpp.lz\
	gfx/pokemon/unown_n/front.animated.2bpp.lz\
	gfx/pokemon/tangela/back.2bpp.lz\
	gfx/pokemon/voltorb/back.2bpp.lz\
	gfx/pokemon/unown_j/front.animated.2bpp.lz\
	gfx/pokemon/mantine/back.2bpp.lz\
	gfx/pokemon/unown_l/front.animated.2bpp.lz\
	gfx/pokemon/piloswine/back.2bpp.lz\
	gfx/pokemon/unown_m/front.animated.2bpp.lz\
	gfx/pokemon/unown_f/front.animated.2bpp.lz\
	gfx/pokemon/natu/back.2bpp.lz\
	gfx/pokemon/unown_a/front.animated.2bpp.lz\
	gfx/pokemon/golem/back.2bpp.lz\
	gfx/pokemon/unown_u/front.animated.2bpp.lz\
	gfx/pokemon/diglett/back.2bpp.lz\
	gfx/pokemon/unown_q/front.animated.2bpp.lz\
	gfx/pokemon/unown_p/front.animated.2bpp.lz\
	gfx/pokemon/unown_c/back.2bpp.lz\
	gfx/pokemon/jynx/back.2bpp.lz\
	gfx/pokemon/golbat/back.2bpp.lz\
	gfx/pokemon/unown_y/front.animated.2bpp.lz\
	gfx/pokemon/unown_g/back.2bpp.lz\
	gfx/pokemon/unown_i/front.animated.2bpp.lz\
	gfx/pokemon/unown_v/back.2bpp.lz\
	gfx/pokemon/forretress/back.2bpp.lz\
	gfx/pokemon/unown_s/back.2bpp.lz\
	gfx/pokemon/unown_r/front.animated.2bpp.lz\
	gfx/pokemon/unown_e/back.2bpp.lz\
	gfx/pokemon/unown_j/back.2bpp.lz\
	gfx/pokemon/unown_b/back.2bpp.lz\
	gfx/pokemon/unown_o/back.2bpp.lz\
	gfx/pokemon/unown_z/back.2bpp.lz\
	gfx/pokemon/unown_w/back.2bpp.lz\
	gfx/pokemon/unown_n/back.2bpp.lz\
	gfx/pokemon/unown_a/back.2bpp.lz\
	gfx/pokemon/unown_m/back.2bpp.lz\
	gfx/pokemon/unown_k/back.2bpp.lz\
	gfx/pokemon/unown_t/back.2bpp.lz\
	gfx/pokemon/unown_x/back.2bpp.lz\
	gfx/pokemon/unown_l/back.2bpp.lz\
	gfx/pokemon/unown_u/back.2bpp.lz\
	gfx/pokemon/unown_q/back.2bpp.lz\
	gfx/pokemon/unown_y/back.2bpp.lz\
	gfx/pokemon/unown_p/back.2bpp.lz\
	gfx/pokemon/unown_i/back.2bpp.lz\
	gfx/pokemon/unown_r/back.2bpp.lz\
	gfx/tilesets/kanto.2bpp.lz\
	gfx/tilesets/johto.2bpp.lz\
	gfx/tilesets/ice_path.2bpp.lz\
	gfx/tilesets/players_room.2bpp.lz\
	gfx/tilesets/pokecenter.2bpp.lz\
	gfx/tilesets/port.2bpp.lz\
	gfx/tilesets/players_house.2bpp.lz\
	gfx/tilesets/mansion.2bpp.lz\
	gfx/tilesets/cave.2bpp.lz\
	gfx/tilesets/tower.2bpp.lz\
	gfx/tilesets/lab.2bpp.lz\
	gfx/tilesets/mart.2bpp.lz\
	gfx/tilesets/game_corner.2bpp.lz\
	gfx/tilesets/train_station.2bpp.lz\
	gfx/tilesets/elite_four_room.2bpp.lz\
	gfx/tilesets/park.2bpp.lz\
	gfx/tilesets/radio_tower.2bpp.lz\
	gfx/tilesets/underground.2bpp.lz\
	gfx/tilesets/dark_cave.2bpp.lz\
	gfx/tilesets/pokecom_center.2bpp.lz\
	gfx/tilesets/battle_tower_inside.2bpp.lz\
	gfx/tilesets/gate.2bpp.lz\
	gfx/tilesets/johto_modern.2bpp.lz\
	gfx/tilesets/traditional_house.2bpp.lz\
	gfx/tilesets/forest.2bpp.lz\
	gfx/tilesets/champions_room.2bpp.lz\
	gfx/tilesets/house.2bpp.lz\
	gfx/tilesets/lighthouse.2bpp.lz\
	gfx/tilesets/facility.2bpp.lz\
	gfx/tilesets/ruins_of_alph.2bpp.lz\
	gfx/pokedex/slowpoke.2bpp.lz\
	gfx/mobile/mobile_trade_sprites.2bpp.lz\
	gfx/mobile/mobile_trade.2bpp.lz\
	gfx/mobile/mobile_trade.tilemap.lz\
	gfx/mobile/mobile_trade.attrmap.lz\
	gfx/mobile/pichu_animated.2bpp.lz\
	gfx/mobile/electro_ball.2bpp.lz\
	gfx/pokedex/slowpoke.2bpp.lz\

