</$objtype/mkfile

OFILES=\
	global.$O\
	main.$O\
	merging.$O\
	mpcomp.$O\
	nullcomp.$O\
	options.$O\
	output.$O\
	packing.$O\
	repcomp.$O\
	spcomp.$O\
	uncomp.$O\
	util.$O\

CFLAGS=$CFLAGS -p

</sys/src/cmd/mkone
